### ISSUE TITLE
eWallet_Mobile App_Android (Registration) #01

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#1]
[Defect_Mobile App #01.xlsx](https://github.com/TNGSB/eWallet/files/565935/Defect_Mobile.App.01.xlsx)

Test Description : To validate error message  displayed when user input invalid character for "Name" field
Expected Result : System should not allow special character input in "Name field" and should prompt error message
Actual Result : System allowed user to proceed to next page upon special character input

Refer attached document for screenshot.

*Apply to both android & IOS

**Comment by mayyeap** [comment]
Name allow special character as some people will key in A/P = anak perempuan (base on their IC)

**Comment by BavaniS** [comment]
name no limitation, should allow generic

**Comment by farahmohamad** [comment]
Retested and passed 2 test cases.

1 IOS and 1 Android.

Build tested IOS 44
Build tested Android 3
[Defect_Mobile App #01-retest.xlsx](https://github.com/TNGSB/eWallet/files/612558/Defect_Mobile.App.01-retest.xlsx)
