### ISSUE TITLE
eWallet_MobileApp_In the RM Transfer process, there is no response or message displayed by the system when the User clicks on the magnifying glass # Live_012

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#100]
What is the "Search ID" here referring to? I do not understand the purpose and after clicking the Magnifying Glass, nothing happens and no message to say ID not found or something.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
search function in transfer is for the user that got a long list of buddy to search for user buddy.

**Comment by ArjunLokanath** [comment]
OK, Closing this defect.. Thanks

Dear Bavani,

Please take note of this as the issue was logged by the FUT user.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
