### ISSUE TITLE
eWallet_MobileApp_User suggests better process flow for the Search ID functionality in the RM Transfer module # Live_015

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#103]
After searching a correct ID, the name is displayed in the list. When key-in other ID and search where it says account does not exist, the list is still there, not cleared. When key-in another correct ID, the name is replaced. How should it behave actually?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
The name will only show and replace when the correct ID key in

**Comment by ArjunLokanath** [comment]
OK noted May

Hi Bavani,

Please advise if this defect can be closed now as per the logic mentioned
by May, This is also one of the issues raised by the FUT user.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
