### ISSUE TITLE
eWallet_MobileApp_User highlights issues encountered while using the "Send Request" button and "Confirm Add" buttons in the RM Transfer module # Live_016

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#104]
What is the purpose of the "Send Request" button? When we search the ID, the name appear in the list, and a "Send Request" button is displayed but cannot be clicked (disabled). After clicking the name, a tick appears at the name and I cannot untick, and another button called "Confirm Add" appears. How does this work actually?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
will check

**Comment by mayyeap** [comment]
fixed! please check next build next wednesday in live

**Comment by ArjunLokanath** [comment]
OK, We will retest this next Wednesday (Nov 23), Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
