### ISSUE TITLE
eWallet_MobileApp_"Confirm Add" button is hidden by the keyboard in the RM Transfer module # Live_017

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#105]
After searching the ID, and ticking the name in the list, the keyboard button is still displayed, hiding the "Confirm Add" button, so user does not realize there is a button to click, unless they manually clear the keyboard.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
ask Bavani for action

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Please advise on this as per mail from May, After searching the ID, and
ticking the name in the list, the keyboard button is still displayed,
hiding the "Confirm Add" button, so user does not realize there is a button
to click, unless they manually clear the keyboard.

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
cover as part of ui/ux cosmetic change, inform arjun to close once you capture in ppt. send me the updated ppt.

**Comment by mayyeap** [comment]
done please close

**Comment by ArjunLokanath** [comment]
Closing this defect as per the comments mentioned above by May and Bavani, Thanks

**Comment by ArjunLokanath** [comment]
Defect has been closed, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
