### ISSUE TITLE
eWallet_MobileApp(Airtime)_Both IOS & Android #097

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#106]
[Defect_Mobile App #97.xlsx](https://github.com/TNGSB/eWallet/files/591389/Defect_Mobile.App.97.xlsx)

Test Description : To verify the error message when user left all the fields in blank
Defect Description : System displayed wrong error message when user left all the fields in blank - apply to both IOS and Android

Refer attachment for POT

**Comment by BavaniS** [comment]
to be covered as part the ui/ux text message
