### ISSUE TITLE
eWallet_MobileApp(Airtime)_ Android #098

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#107]
[Defect_Mobile App #98.xlsx](https://github.com/TNGSB/eWallet/files/591393/Defect_Mobile.App.98.xlsx)

Test Description : To verify the error message when user insert invalid PIN
Defect Description : System did not display error message for Android however IOS displayed accordingly

Refer attachment for POT.

**Comment by mayyeap** [comment]
pleasse check again

**Comment by BavaniS** [comment]
check in liv env and close

**Comment by farahmohamad** [comment]
Retested in live env, however there are no error message displayed upon invalid PIN.

Refer the screenshot.

![screenshot_20161121-103515](https://cloud.githubusercontent.com/assets/23113211/20468915/6a19a054-afd6-11e6-9f69-407e6718cf13.png)

**Comment by mayyeap** [comment]
fixed, please check on new build

**Comment by mayyeap** [comment]
Farah, please help Arjun to check this part and closed this case

**Comment by farahmohamad** [comment]
Hi May,

Tested with build 38 for android and 46 for IOS.

Attached POT for your reference.

Thanks.
[Defect_Mobile App #98-retest.xlsx](https://github.com/TNGSB/eWallet/files/626416/Defect_Mobile.App.98-retest.xlsx)
