### ISSUE TITLE
eWallet_MobileApp_User highlights concern regarding the Buddy list # Live_018

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#108]
Once a buddy has been added, it will be listed in the Transfer page. What is the grey line across with a "pipe" character below the Buddy list caption for?
It looks like a field that user can click.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
![capture](https://cloud.githubusercontent.com/assets/23113169/20349859/34bfdd3e-ac47-11e6-9fef-f502ed7497ca.PNG)
