### ISSUE TITLE
eWallet_MobileApp(Transaction History)_ IOS only #099

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#109]
[Defect_Mobile App #99.xlsx](https://github.com/TNGSB/eWallet/files/591400/Defect_Mobile.App.99.xlsx)

Test Description : To verify blank email input error message
Defect Description : System displayed IOS error message incorrect

Refer attachment for POT

**Comment by mayyeap** [comment]
fix previously, pleasse check again

**Comment by BavaniS** [comment]
fixed in new build, to recheck in liv env and close.

**Comment by farahmohamad** [comment]
Retested for both android and IOS.

IOS are fixed. System will not allow user to click the "Send" button.
However, for Android, system allow us to click the "Send" button and displayed "Incomplete information" error message.

Kindly confirm, if the email field is blank, user are allowed to click on the "Send" button or not? 
The result for both android and IOS are not sync.

Refer attachment for POT for android screenshot.
![screenshot_20161121-104139](https://cloud.githubusercontent.com/assets/23113211/20469159/b5f98f50-afd8-11e6-8da0-c47ec4e74ad5.png)
![screenshot_20161121-104152](https://cloud.githubusercontent.com/assets/23113211/20469160/b5fcea88-afd8-11e6-99c0-0c82222b9056.png)

**Comment by mayyeap** [comment]
Fixed, it will show incomplete information

**Comment by farahmohamad** [comment]
Hi May,

I have tested with build 42 for IOS and the error message displayed as "Please enter a correct email" instead of "information incomplete"

![img_1617](https://cloud.githubusercontent.com/assets/23113211/20514084/fe62681a-b0c4-11e6-9023-5f9a561bc203.PNG)


Refer the screenshot below

**Comment by mayyeap** [comment]
Hi Farah, 

For the time being, this will be the error message show for IOS & Android, Error message : Incomplete information will be change together with the icon change in future. Please close this case.

THanks

**Comment by farahmohamad** [comment]
Hi May,

Noted. 

Will close this defect accordingly.
