### ISSUE TITLE
eWallet_MobileApp_Font size of the Terms and Conditions are too small for the User's proper reading and understanding # Live_019

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#110]
T&C content is too small, User cannot read and the User also cannot tilt to Landscape and cannot make the font bigger to read.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
will ask developer check

**Comment by BavaniS** [comment]
cover as part of ui/ux change, inform arjun to close once you capture in ppt.

**Comment by mayyeap** [comment]
done, Arjun pls close

**Comment by ArjunLokanath** [comment]
Closing this defect as per the comments mentioned above by May and Bavani, Thanks

**Comment by ArjunLokanath** [comment]
Defect has been closed, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
