### ISSUE TITLE
eWallet_MobileApp_The FAQ content is not correctly updated as highlighted by the FUT User # Live_020

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#112]
FAQ Content was not updated. For FUT, I believe it needs to be ready so that users can read & provide feedback on the FAQ whether it is clear and sufficient.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
Faq is not yet ready. will be ready end month. please check in uat end month
