### ISSUE TITLE
eWallet_MobileApp_User highlights that there is no control of maximum 6 digits in the field on the Change PIN page # Live_021

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#113]
In the Change PIN page, there is no control of maximum 6 digits in the field. It only check upon clicking Next. Can we control the entry field to be 6 digits only?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
cosmetic, ask Bavani

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Kindly advise on this as well, This was raised by the FUT user

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
may, inform arjun to close once you update this in your ppt as cosmetic of ui/ux changes

**Comment by mayyeap** [comment]
done, Arjun please close

**Comment by ArjunLokanath** [comment]
Closing this defect as per the  comments above from May and Bavani, Thanks

**Comment by ArjunLokanath** [comment]
Defect has been closed, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
