### ISSUE TITLE
eWallet_MobileApp_Frequent issue on receiving OTP # Live_022

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#117]
Can you please look into this if there is connectivity issue between Mobility One and Telco and that is causing the bottleneck.

**Comment by ArjunLokanath** [comment]
Attached below is the email trail on this issue to help clarify:

Yee Kee Sin keesin@mobilityone.com.my
Nov 14 (1 day ago)

to Bavani, Shanize, Xavier, Lim, May, ccc, support, Wan, Asma, Juliana, Raja, Ahmad, me 
Dear Bavani

We have forwarded the SMS request to the shortcode/SMSC without delay, and the retry is between the operator SMSC and the mobile.
Every SMS has its validity timestamp, if the SMSC fail to send the SMS at the first attempt, it will be periodically retried as long as the SMS still valid.

Thanks
Kee Sin

From: Bavani Shanmugam [mailto:bavani@touchngo.com.my] 
Sent: Monday, 14 November, 2016 7:54 AM
To: Yee Kee Sin keesin@mobilityone.com.my; 'Shanize Kua' shanize@mobilityone.com.my; 'Xavier Wong' xavier@ablglobal.com; 'Lim (APACVenture)' lim@apacventure.com; 'May (APAC Venture)' may@apacventure.com; ccc@mobilityone.com.my; support@mobilityone.com.my
Cc: Wan Malya Masitah Wan Hussein malya.masitah@touchngo.com.my; Asma Hanim Ahmad Marikan asma.hanim@touchngo.com.my; Juliana Abu Bakar juliana@touchngo.com.my; Raja Jesmyra Raja Abdullah jesmyra@touchngo.com.my; Ahmad Suffian Osman suffian@touchngo.com.my; 'Arjun Lokanath' arjun.lokanath@appsync.sg
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

Hi Kee Sin,

What’s the response time we talking here for highlighted below? Due we have our transaction time out as well..

Thanks, 
Bavani

From: Yee Kee Sin [mailto:keesin@mobilityone.com.my] 
Sent: Friday, 11 November, 2016 8:13 PM
To: 'Shanize Kua'; Bavani Shanmugam; 'Xavier Wong'; 'Lim (APACVenture)'; 'May (APAC Venture)'; ccc@mobilityone.com.my; support@mobilityone.com.my
Cc: Wan Malya Masitah Wan Hussein; Asma Hanim Ahmad Marikan; Juliana Abu Bakar; Raja Jesmyra Raja Abdullah; Ahmad Suffian Osman; 'Arjun Lokanath'
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

Dear All

Please find the reply below from the uplink.

We have checked the submission within a specific period of time and confirmed that the delay only happened on this number alone.
Thus, it is proven that the route works fine as delivery towards other numbers are immediate.

We suspect the network unable to reach the number (might be in absent condition) or having low coverage during the message submission.
If the subscriber is not available on the first delivery attempt, the message will remain in the retry scheme and will be periodically retried for delivery until success or validity expiration.

Hope this explains. We can see the delivery after few minutes is instant on this number.

Thanks
Kee Sin

From: Yee Kee Sin [mailto:keesin@mobilityone.com.my] 
Sent: Friday, 11 November, 2016 2:37 PM
To: 'Shanize Kua' shanize@mobilityone.com.my; 'Bavani Shanmugam' bavani@touchngo.com.my; 'Xavier Wong' xavier@ablglobal.com; 'Lim (APACVenture)' lim@apacventure.com; 'May (APAC Venture)' may@apacventure.com; 'ccc@mobilityone.com.my' ccc@mobilityone.com.my; 'support@mobilityone.com.my' support@mobilityone.com.my
Cc: 'Wan Malya Masitah Wan Hussein' malya.masitah@touchngo.com.my; 'Asma Hanim Ahmad Marikan' asma.hanim@touchngo.com.my; 'Juliana Abu Bakar' juliana@touchngo.com.my; 'Raja Jesmyra Raja Abdullah' jesmyra@touchngo.com.my; 'Ahmad Suffian Osman' suffian@touchngo.com.my; 'Arjun Lokanath' arjun.lokanath@appsync.sg
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

Dear Shanize

We noticed 4  SMS-es highlight below have been delivered with delayed at uplink carrier. We have raised a ticket to uplink carrier, will revert once we hear from them.

2016-11-10 13:58:28
2016-11-10 13:58:48
4F19DBF37C734E91BAB
60193513020
3.6957.58240c854a0da3.09639472.853386903
DELIVRD
2016-11-10 13:57:22
2016-11-10 18:32:58
3A0A8CC82983440A94C
60193513020
3.6957.58240c44476576.43448904.2054512490
DELIVRD
2016-11-10 13:45:27
2016-11-10 18:32:58
652878836DF54DC8B5C
60193513020
3.6957.58240977cac5e7.70723879.634578038
DELIVRD
2016-11-10 13:43:51
2016-11-10 18:32:55
55554B8EC26B4389B4F
60193513020
3.26047.5824091879a575.26528976.1551183183
DELIVRD
2016-11-10 13:42:48
2016-11-10 18:32:55
75FE8519C56C4584BF2
60193513020
3.26047.582408d9c11424.16771988.509955260
DELIVRD
2016-11-10 13:41:34
2016-11-10 13:55:04
9696D124DC244A21B21
60193513020
3.26047.5824088e91e282.33122093.19138876
DELIVRD

Thanks
Kee Sin

From: Shanize Kua [mailto:shanize@mobilityone.com.my] 
Sent: Friday, 11 November, 2016 2:12 PM
To: 'Bavani Shanmugam' bavani@touchngo.com.my; 'Yee Kee Sin' keesin@mobilityone.com.my; 'Xavier Wong' xavier@ablglobal.com; 'Lim (APACVenture)' lim@apacventure.com; 'May (APAC Venture)' may@apacventure.com; ccc@mobilityone.com.my
Cc: 'Wan Malya Masitah Wan Hussein' malya.masitah@touchngo.com.my; 'Asma Hanim Ahmad Marikan' asma.hanim@touchngo.com.my; 'Juliana Abu Bakar' juliana@touchngo.com.my; 'Raja Jesmyra Raja Abdullah' jesmyra@touchngo.com.my; 'Ahmad Suffian Osman' suffian@touchngo.com.my; 'Arjun Lokanath' arjun.lokanath@appsync.sg
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

Hi Bavani,
The request was yesterday?

Hi Kee Sin,
Please assist to check the delay in receiving OTP

Thank you

From: Bavani Shanmugam [mailto:bavani@touchngo.com.my] 
Sent: Friday, November 11, 2016 11:36 AM
To: Shanize Kua shanize@mobilityone.com.my; 'Yee Kee Sin ' <IMCEAMAILTO-keesin+40mobilityone+2Ecom+2Emy@touchngo.prod>; 'Xavier Wong' xavier@ablglobal.com; 'Lim (APACVenture)' lim@apacventure.com; 'May (APAC Venture)' may@apacventure.com
Cc: Wan Malya Masitah Wan Hussein malya.masitah@touchngo.com.my; Asma Hanim Ahmad Marikan asma.hanim@touchngo.com.my; Juliana Abu Bakar juliana@touchngo.com.my; Raja Jesmyra Raja Abdullah jesmyra@touchngo.com.my; Ahmad Suffian Osman suffian@touchngo.com.my; 'Arjun Lokanath' arjun.lokanath@appsync.sg
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

019 351 3020

Xavier,
I need numbers of sms sent out from ABL then we can quantify numbers of sms received and out from mobility one.

From: Shanize Kua [mailto:shanize@mobilityone.com.my] 
Sent: Friday, 11 November, 2016 10:12 AM
To: Bavani Shanmugam; 'Yee Kee Sin '; 'Xavier Wong'; 'Lim (APACVenture)'; 'May (APAC Venture)'
Cc: Wan Malya Masitah Wan Hussein; Asma Hanim Ahmad Marikan; Juliana Abu Bakar; Raja Jesmyra Raja Abdullah; Ahmad Suffian Osman; 'Arjun Lokanath'
Subject: RE: TNG E-Wallet Friendly User Trial (FUT) Briefing

Hi Bavani,

Can you please provide the mobile phone no and date for further checking

Thank you

Shanize

From: Bavani Shanmugam [mailto:bavani@touchngo.com.my] 
Sent: Thursday, November 10, 2016 5:50 PM
To: Shanize Kua shanize@mobilityone.com.my; Yee Kee Sin <IMCEAMAILTO-keesin+40mobilityone+2Ecom+2Emy@touchngo.prod>; Xavier Wong xavier@ablglobal.com; Lim (APACVenture) lim@apacventure.com; 'May (APAC Venture)' may@apacventure.com
Cc: Wan Malya Masitah Wan Hussein malya.masitah@touchngo.com.my; Asma Hanim Ahmad Marikan asma.hanim@touchngo.com.my; Juliana Abu Bakar juliana@touchngo.com.my; Raja Jesmyra Raja Abdullah jesmyra@touchngo.com.my; Ahmad Suffian Osman suffian@touchngo.com.my; Arjun Lokanath arjun.lokanath@appsync.sg
Subject: FW: TNG E-Wallet Friendly User Trial (FUT) Briefing

Hi Shanize, 

We getting frequent issue on receiving OTP, can you please look into this if the connectivity between Mobility One and Telco’s is the bottleneck. 

Hi Xavier, Lim,

Kindly advise from your end as well.

Thanks, 
Bavani

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Please advise on this OTP issue, Can we close this based on the explanation provided by keesin@mobilityone (email has been attached in the comment above for your kind reference), Thanks

**Comment by BavaniS** [comment]
MO will look into the shortcode, keep it open and assign to me.

**Comment by ArjunLokanath** [comment]
Noted Bavani, Keeping this open as advised.

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
changed shortcode, i will close this now for monitoring.

**Comment by markshermanp** [comment]
Reopening this defect as OTP is again failing. Upgrading defect severity to Sev-1
