### ISSUE TITLE
eWallet_PaymentsModule_Issue encountered in payment to Little Taiwan # Live_023

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#118]
1. Payment request successfully received but the request amount was strange. The amount "930000000000001" was requested for payment( see attached log). Expected amount should be "930" (cent form)
2. Server has successfully processed and response with "INSUFFICIENT BALANCE" status code (62) to the app. No locking from the back-end.

**Comment by ArjunLokanath** [comment]
Kindly refer the email trail below for further details on this issue:

From: Jayden [mailto:jayden@ablglobal.com] 
Sent: Monday, 14 November, 2016 11:55 AM
To: Raja Jesmyra Raja Abdullah; may@apacventure.com; lim@apacventure.com
Cc: Xavier Wong xavier@ablglobal.com (xavier@ablglobal.com); Jason Pang jason@ablglobal.com (jason@ablglobal.com); Juliana Abu Bakar; Bavani Shanmugam; Farhad Fahd Othman; Dinesh Arunatheym
Subject: Re: Payment to Little Taiwan

Hi Myra,

We have check from the back-end and found that:
 Payment request successfully received but the request amount was strange. The amount "930000000000001" was requested for payment( see attached log). Expected amount should be "930" (cent form)
 Server has successfully processed and response with "INSUFFICIENT BALANCE" status code (62) to the app. No locking from the back-end.

In conclusion, suspecting error/bug caused from front-end.

Hi Lim/May,

Kindly assist on this. 
Inline image 1

Regards,
Jayden

On Mon, Nov 14, 2016 at 11:30 AM, Raja Jesmyra Raja Abdullah jesmyra@touchngo.com.my wrote:
Hi All,

Farhad tried to make payment at Little Taiwan on Friday and apparently it failed. After scanning the QR code (both on receipt and standee), Farhad input the amount and 6 digit PIN however it keeps on loading for more than 5 mins.

I tried making payment again today and encountered the same problem as Farhad. The amount that we input in is RM9.30.

Please find attached the QR code that we scanned and the page that keeps on loading and without getting the page where it says “RMXX has been deducted from your wallet”.

Hope you can assist on this matter.

Thanks

Raja Jesmyra (Myra),
Digital Wallet
Touch ‘n Go Sdn Bhd
Level 5, Tower 6, Avenue 5, Bangsar South,
No 8, Jalan Kerinchi,
59200 Kuala Lumpur
Mob : +6019-2375878
Email: jesmyra@touchngo.com.my

**Comment by mayyeap** [comment]
fix, will release next build

**Comment by BavaniS** [comment]
arjun - do check and close
