### ISSUE TITLE
eWallet_MobileApp_Registration failed as it took very long to receive SMS and still could not register as the latest OTP had not been received by the User # Live_024

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#119]
Tried creating login . Below is the issue :-
 
    1) OTP did not arrive after Many attempts (> 3) .
 
    2) I received an OTP eventually  while the resend OTP was activated with countdown. Therefore, I could not use the received OTP and I did not receive the new OTP either.
 
         I could not try to re-register anymore as I guess you have my info as pending registration in your backend as it says “ login_id already exist”. You have time period for the pending registration to expire…?
 
 
   Please look into why it takes so long to receive a SMS and still could not register due to the latest OTP hasn’t arrived.

**Comment by ArjunLokanath** [comment]
Please refer the email trail below for further details on this issue:

From: Thana Letchumi Ponudurai 
Sent: Monday, 14 November, 2016 2:43 PM
To: Bavani Shanmugam; Xavier Wong; 'Jason Pang'
Subject: Wallet App - Registration Failed

Hi,

  Tried creating login . Below is the issue :-

```
1) OTP did not arrive after Many attempts (> 3) .

2) I received an OTP eventually  while the resend OTP was activated with countdown. Therefore, I could not use the received OTP and I did not receive the new OTP either.

     I could not try to re-register anymore as I guess you have my info as pending registration in your backend as it says “ login_id already exist”. You have time period for the pending registration to expire…?
```

   Please look into why it takes so long to receive a SMS and still could not register due to the latest OTP hasn’t arrived.

  Thanks

Regards,
Thana

**Comment by raymondabl** [comment]
A brief on how sms works:

1 --> 2 --> 3--> 4 --> 5
APAC --> ABL --> MobilityOne --> Telco Operator --> User

1 - sent to ABL successfully
2 - sent to MobilityOne successfully
3 - out of control (e.g. MO offline)
4 - out of control (e.g. Telco Operator offline)
5 - out of control (e.g. User offline)

SMS is known to have reliability issue since involving multiple parties. 

Take note:
1.  TNG has a policy on max OTP per day which is 5 times / day / IC. 
2. Each pending registration will be cleared every 15 minutes. 

Hope it helps.

**Comment by ArjunLokanath** [comment]
Noted with Thanks Raymond

Hi Bavani,

This issue was logged by the User and I am guessing for the User it is just
frustrating to wait for a very long time to receive the SMS as I also faced
the issue today and from a User's perspective, it does not really matter
where it gets stuck and the User will just raise as a defect when
encountered this issue,

So kindly advise how to take this forward? Is it possible for us to check
with the external parties on Steps 3 & 4 as mentioned in Raymond's email as
I don't have a contact there to connect with them.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
duplicate #117
