### ISSUE TITLE
eWallet_MobileApp/Portal_The Transaction History Reference Number displayed on the Mobile App is not in sync with the Portal (Back end) # Live_025

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#120]
Based on what the reference number for the transaction history is generated and meaningful to users? What info is received/passed to/from ABL when a trx success?
 
There is a customer log complain by giving a ref.no. how this is being mapped to backend to create new case in admin portal?

**Comment by ArjunLokanath** [comment]
Refer to the email below for the full details on this issue:

Bavani Shanmugam bavani@touchngo.com.my
Nov 14 (1 day ago)

to May, me, Wee, Xavier, lim 
Hi May, 

Based on what the reference number for the transaction history is generated and meaningful to users? What info is received/passed to/from ABL when a trx success?

I have a customer log complain by giving a ref.no. how this is being mapped to backend to create new case in admin portal.

Sort it out with Wee Jay, get it mitigated by next build.

Thanks,
Bavani

**Comment by mayyeap** [comment]
ABL will match the reference number

**Comment by raymondabl** [comment]
We have mitigated this problem. Please test it out on next build.

**Comment by ArjunLokanath** [comment]
Hi Raymond,

Noted and is the next build expected to be released tomorrow (Nov-18)?
Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by raymondabl** [comment]
@ArjunLokanath Yes, already deployed in the dev server

**Comment by ArjunLokanath** [comment]
Hi Raymond,

This issue was found in the Live environment hence expect the User to
retest in the same Live environment itself.. Thanks and let us know once
available

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by JasonABL** [comment]
Hi,

Please retry this in both dev and uat environment. Thanks.

Regards,
Jason

**Comment by ArjunLokanath** [comment]
Hi Zharfan, Please help to retest this defect tomorrow.. Thanks
