### ISSUE TITLE
e-Wallet_WebAdmin (Commission Mgmt)_15112016 #101

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#121]
Test Description : To validate the values parameter for 'Add Commission Profile' page mandatory fields - Name 
Expected Result : System should prompt an error message after system validate the input of special character

Actual Result : System does not validate Name field which should only for alphanumeric

Refer attachment for reference
[Defect_BackOffice_#101.xlsx](https://github.com/TNGSB/eWallet/files/591510/Defect_BackOffice_.101.xlsx)

**Comment by JasonABL** [comment]
duplicated with #102?

**Comment by muhdzhrfn** [comment]
It is different page,this one for add commission profile page

**Comment by JasonABL** [comment]
Hi,

Thanks for pointing out. 

We can make can make it no special character allowed, but profile name might need special character. Will need clarify with Bavani.

**Comment by BavaniS** [comment]
name can be generic with special char

ABL spec doc to be changed from alphanumeric to text/string
