### ISSUE TITLE
e-Wallet_WebAdmin (Commission Mgmt)_15112016 #102

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#122]
Test Description : To validate the values parameter for 'Add Cost of Fund Profile' page mandatory fields - Name 
Expected Result : System should prompt an error message after system validate the input of special character

Actual Result : System does not validate Name field which should only for alphanumeric

Refer attachment for reference
[Uploading Defect_BackOffice_#102.xlsx…]()

**Comment by JasonABL** [comment]
We can make can make it no special character allowed, but profile name might need special character. Will need clarify with Bavani.

**Comment by BavaniS** [comment]
name can be generic with special char

ABL to ensure the changes reflected in system
