### ISSUE TITLE
eWallet_MobileApp/Portal_Unsuccessful Reload Transaction # Live_026

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#123]
Whenever there is a Reload transaction, iPay will send a response message on the fund payment to both the Mobile App as well as the eWallet Back end system, However the Mobile App (Front end) has failed to receive this message from iPay and hence has not sent a further message to eWallet Back end system to process the transaction and therefore there was a Unsuccessful Reload Transaction,

Investigation is still in progress and fix is yet pending.

**Comment by ArjunLokanath** [comment]
Please refer to the email trail below for further details on this issue:

From: integration.waihong@ipay88.com.my [mailto:integration.waihong@ipay88.com.my] On Behalf Of TechSupportMY(9)
Sent: Monday, 14 November, 2016 12:12 PM
To: Jason Pang
Cc: TechSupport MY; Bavani Shanmugam; Xavier Wong; Lai Seow Yong (赖少荣); Jayden; Raymond Chai; Mohd Radzi Abdul Hamid; Lim (APACVenture); Grace Ng; may@apacventure.com; dengting; Shahrul Nizam Mazlan; Faridah Ismail; Sharidzaly Busu
Subject: Re: Unsuccessful Reload Transaction

Dear Jason,

Sorry for late response.
Based on your statement, you are correct that reload/top-up not success is unrelated to whether BackendURL need to reply with "RECEIVEOK" as iPay88 will still send response data as long as payment success.  

But we do recommend merchant to reply with "RECEIVEOK" once get backend response data from ipay88. 

Sorry for the misunderstanding and inconvenience caused on the previous replied email.

Best Regards,

Lee Wai Hong

On Fri, Nov 11, 2016 at 3:17 PM, Jason Pang jason@ablglobal.com wrote:
Hi Wai Hong,

As a summary, is not mandate to have callback response from Backend server to determine the ipay88 transaction is successful. Therefore, your statement transaction unsuccessful was due to no callback response is not valid.

Please correct me if im wrong.

Sent from my iPhone

On 11 Nov 2016, at 2:48 PM, TechSupportMY(9) techsupport@ipay88.com.my wrote:

Hi Jason/Bavani,

Do refer to my inline reply (PINK).

Best Regards,

Lee Wai Hong

On Fri, Nov 11, 2016 at 12:39 PM, Jason Pang jason@ablglobal.com wrote:
Hi Bavani, 

Please clarify with ipay88 if our understanding is correct as below.
1. Mobile (APAC) will trigger ipay88 to perform top up. 
   Transaction REQUEST will send from APP(apac) to ipay88 to perform topup, and ipay88 will return RESPONSE data to both ResponseURL and BackendURL when payment success.
2. Ipay88 will only send response to Mobile and callback to Backend server if transaction is successful at ipay88. 
   Yes ipay88 will return RESPONSE data to both ResponseURL and BackendURL when payment success. 
   Currently 
   a) ResponseURL set as http://110.74.178.213/remote/ipay88client/fpxIpay88.client (for FPX payment) 
   b) ResponseURL set as http://110.74.178.213/remote/ipay88client/btIpay88.client (for credit card bind card (BT))
   c) ResponseURL set as http://110.74.178.213/remote/ipay88client/scIpay88.client (for credit card subsequent charge(SC))
   while all transaction type will have BackendURL set as http://110.74.178.210/t/1.0/wallet/topup/callback
3. Callback to backend server is as notification purpose only and does not affect ipay88 status. Not sure on this inquiry as it more on how TnG system architecture work after get RESPONSE data.
4. With or without response callback from Backend server to ipay88, mobile (apac) need to call Backend for topup. Not sure on this inquiry on whether mobile(apac) to perform the callback as it more on how TnG system architecture work.

Regards,
Jason

Sent from my iPhone

On 11 Nov 2016, at 11:43 AM, Bavani Shanmugam bavani@touchngo.com.my wrote:

++

From: n.afifah@ipay88.com.my [mailto:n.afifah@ipay88.com.my] On Behalf Of TechsupportMY(5)
Sent: Friday, 11 November, 2016 11:35 AM
To: Xavier Wong
Cc: Mohd Radzi Abdul Hamid; Bavani Shanmugam; Lim (APACVenture); Grace Ng; TechSupport MY
Subject: Re: Unsuccessful Reload Transaction

Dear Xavier,

Based on our transaction log, it show all the payment is success and ipay88 server had attempted few times return payment success status to ABL BackendURL (http://110.74.178.210/t/1.0/wallet/topup/callback) but each of the attempt show ABL BackendURL not properly response/reply back to ipay88 server for those transactions. Thus it caused reload not successful.

Below is the sample log for BackendURL response from your system.
Backend Post Status
CreateDate
Response Code
Response Data
11/9/2016 10:50:04 AM 
200 

11/9/2016 10:48:00 AM 
200 

11/9/2016 10:46:11 AM 
200 

Under normal circumstance, "Response Code"  will be 200 and the Response Data is the expected reply "RECEIVEOK" or "OK" reply from merchant.
Below is the sample log for BackendURL response from your system which your BackendURL did reply "OK" to ipay88.
Backend Post Status
CreateDate
Response Code
Response Data
11/11/2016 10:56:00 AM 
200 
OK 
11/11/2016 10:54:11 AM 
200 

Need your side to check on is there any issue on ABL BackendURL or performance issue during that time.

Best regards,

Nor Afifah
iPay88 Technical Support

On Fri, Nov 11, 2016 at 9:23 AM, Grace Ng graceng@ipay88.com.my wrote:
Dear Tech Support

Please assist below.

Thank  you!

Best regards,

<image001.png>
Grace Ng
Assistant Manager | Merchant Relationship
iPay88 Sdn Bhd | Mobile88.com Sdn Bhd
Suite 2A-18-2, 18th Floor, Block 2A, Plaza Sentral, Jalan Stesen Sentral 5, 50470 Kuala Lumpur, Malaysia
M : +6016 247 7200 | T : +603 2261 4668 | F : +603 2261 4663
E : graceng@ipay88.com.my | W : www.ipay88.com

From: Lim (APACVenture) [mailto:lim@apacventure.com] 
Sent: Thursday, 10 November, 2016 6:55 PM
To: Bavani Shanmugam bavani@touchngo.com.my
Cc: Xavier Wong xavier@ablglobal.com; Grace Ng graceng@ipay88.com.my; Mohd Radzi Abdul Hamid m.radzi@touchngo.com.my
Subject: Re: Unsuccessful Reload Transaction
Importance: High

Hi Grace, 

Can you please retrieve your log and investigate each following failed transaction?
We need to know what kind of result you returned to us through your response and callback URL for all those failed FPX.

The scenario
1. End user does not complete their FPX reload, is either they end/back the page or the bank page idling infinitely 
2. Then, we received failed from your end through response URL and callback URL
3. Hence, we do not perform the reload to end user
4. However, the bank somehow still deduct the money from end user's bank account

Thank you. 

## 

Lim
IM.CEO
email. lim@apacventure.com 
mobile. +6017-5527628  

APAC Venture Sdn. Bhd. (936959-H) (GST# 001725054976) 
tel. +603-77334080
fax. +603-77339080
add. B-5-30, 5th Floor, 10 Boulevard, PJU 6A, 47400 Petaling Jaya, Selangor, Malaysia.

avast! Distributor & WeChat Preferred Partner

On 10 Nov 2016, at 6:29 PM, Bavani Shanmugam bavani@touchngo.com.my wrote:

Hi Grace,

This is the issue highlighted earlier today on FPX transaction failed but deducted from bank account. Can you extract the log to address if it is success or failure case from your end?

Thanks,
Bavani

From: Xavier Wong [mailto:xavier@ablglobal.com] 
Sent: Thursday, 10 November, 2016 6:31 PM
To: 'Lim (APACVenture)'; Bavani Shanmugam
Subject: Unsuccessful Reload Transaction

Hi Lim,

As requested by Bavani, here is the unsuccessful reload.

No
Date Time
Payment Host
References No
eWallet ID
Reload Amount
Status
Remark
5
2016-11-02 20:14:53
IPAY88(FPX)
T112678279300

10.00
FAILED
Not successful top up to wallet
41
2016-11-04 10:46:20
IPAY88(FPX)
T112729602400

10.00
FAILED
Not successful top up to wallet
57
2016-11-05 20:44:12
IPAY88(FPX)
T112779680500

10.00
FAILED
Not successful top up to wallet
65
2016-11-07 18:19:56
IPAY88(FPX)
T112837331500

10.00
FAILED
Not successful top up to wallet
70
2016-11-09 05:23:14
IPAY88(FPX)
T112884095500

10.00
FAILED
Not successful top up to wallet
72
2016-11-09 10:45:17
IPAY88(FPX)
T112889268400

10.00
FAILED
Not successful top up to wallet

Xavier Wong
APTUS BUSINESS LOGIC PTE. LTD.
Mobile: +6012 217 7117

**Comment by JasonABL** [comment]
Please seek advise from Bavani as this issue need Apac to rectify why mobile not sending request  to TnG Backend for iPay88 Top Up.

**Comment by mayyeap** [comment]
we have check and this issue is cause by user behaviour as they close the app, of cut off the reload half way which mean money is successfully deducted from the bank but it fail to direct to mobile page therefore we did not received any response from ipay to perform reload.

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Seek your advise on the issue below, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
apac never receive callback from ipay because user never complete all 3 pages till end.

ipay removing additional page on fpx (25 Nov)

arjun - retest half way and exit, see if same issue again.

**Comment by muhdzhrfn** [comment]
Fixed
