### ISSUE TITLE
eWallet_MobileApp(Reload)  #105

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#126]
[Defect_Mobile App #105.xlsx](https://github.com/TNGSB/eWallet/files/593552/Defect_Mobile.App.105.xlsx)

Defect Description : System displayed a successful message and automatically redirect user to "Credit/Debit Card" page before the countdown counter time out

Test Description : To verify error message when user exceeded the countdown timer for credit card detail input

Refer attachment for POT

**Comment by BavaniS** [comment]
apac to check if same case in live environment

**Comment by mayyeap** [comment]
i try the scanario, but it show failed message instead of success. Can you show me again. We just display the message if ipay send us correct response.

Thanks

**Comment by farahmohamad** [comment]
Hi May,

Tested with build 38 for android and 46 for IOS.

Attached POT for your reference.

Thanks.
[Defect_Mobile App #105-retest.xlsx](https://github.com/TNGSB/eWallet/files/626639/Defect_Mobile.App.105-retest.xlsx)
