### ISSUE TITLE
eWallet_MobileApp_Virtual Keypad on the Airtime topup does not go back down after pressing the 'Done' button # 112

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#139]
After the User enters the Mobile number and press the "Done" button, The Virtual keypad does not go back down so the User has to click outside the Keypad so that he can proceed with the next step, Therefore what is the meaning of having the 'Done' button here when it does not do anything

**Comment by mayyeap** [comment]
will check with developer

**Comment by mayyeap** [comment]
fixed. Farah please check in new build

**Comment by farahmohamad** [comment]
Tested for android with build 38 and IOS build 46, the keyboard went down upon clicking "Done".
Therefore, close this defect.
