### ISSUE TITLE
eWallet_MobileApp-Movie Purchase(Dev Env) #113

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#140]
[Defect_Mobile App #113.xlsx](https://github.com/TNGSB/eWallet/files/596790/Defect_Mobile.App.113.xlsx)

Defect Description : For Iphone only, design error when user click on the dropdown list
Test Description : To verify the "region" dropdown list functionality

Refer the attachment for POT.

**Comment by mayyeap** [comment]
The page is merhant page and control by merchant

**Comment by farahmohamad** [comment]
<Farah 21.11.16>
To close this defect as this is not maintain by mobile application
