### ISSUE TITLE
eWallet_MobileApp-Movie Purchase(Dev Env) #114

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#141]
[Defect_Mobile App #114.xlsx](https://github.com/TNGSB/eWallet/files/596800/Defect_Mobile.App.114.xlsx)

Defect Description : System to display wrong error message for invalid phone number
Test Description : To confirm on purchase by inserting a invalid phone number

Refer the attachment for POT.

**Comment by mayyeap** [comment]
This is error message from merchant

**Comment by farahmohamad** [comment]
To close this defect as this is not maintain by mobile application.
