### ISSUE TITLE
eWallet_MobileApp-Purchase Air Ticket (Dev Env) #115

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#142]
[Defect_Mobile App #115.xlsx](https://github.com/TNGSB/eWallet/files/596802/Defect_Mobile.App.115.xlsx)

Defect Description : Unable to go through the next page. The air ticket displayed as blank page
Test Description : To verify the navigation from "Selection Time" page to "Contact Information" page

Refer the attachment for POT.

**Comment by mayyeap** [comment]
Please contact airpaz.

**Comment by farahmohamad** [comment]
Reassigned as this is Air Paz related

**Comment by farahmohamad** [comment]
Tested with development application, build 48 for IOS.

Therefore, close this defect.

[Defect_Mobile App #115-retest.xlsx](https://github.com/TNGSB/eWallet/files/633174/Defect_Mobile.App.115-retest.xlsx)
