### ISSUE TITLE
eWallet_MobileApp-Purchase Air Ticket (Dev Env) #116

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#143]
[Defect_Mobile App #116.xlsx](https://github.com/TNGSB/eWallet/files/596807/Defect_Mobile.App.116.xlsx)

Defect Description : User are not redirect to payment gateway page. Current page keep on loading
Test Description : To validate user eWallet account balance - transaction more than RM1500

Refer the attachment for POT.

**Comment by mayyeap** [comment]
Please check with airpaz. Websit loading.

**Comment by farahmohamad** [comment]
Reassigned as this is related to AirPaz

**Comment by BavaniS** [comment]
tpa not available for above 1500.

expectation trx should cancel and pop up error msg

**Comment by farahmohamad** [comment]
Tested with dev build for IOS, build 48.

Close this defect.
[Defect_Mobile App #116-retest.xlsx](https://github.com/TNGSB/eWallet/files/633197/Defect_Mobile.App.116-retest.xlsx)
