### ISSUE TITLE
eWallet_MobileApp-Reload via Credit Card / Debit Card (Live Env) #117

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#144]
[Defect_Mobile App #117.xlsx](https://github.com/TNGSB/eWallet/files/596808/Defect_Mobile.App.117.xlsx)

Defect Description :Bank account balance are not deducted due to reload via debit card
Test Description : To verify the successful transaction 

Refer the attachment for POT.

**Comment by mayyeap** [comment]
Farah, please explain more on this? im not really sure what do u mean

**Comment by mayyeap** [comment]
Hi Farah, please check with ipay. Thanks

**Comment by BavaniS** [comment]
ipay and acquirer has deducted immediate, problem with user individual bank

farah - can you try similar with maybank or other bank account?

**Comment by farahmohamad** [comment]
I have retested with Maybank successful transaction.

Close this defect and will update the screenshot later
