### ISSUE TITLE
eWallet_MobileApp-Reload via FPX (Live Env) #118

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#145]
[Defect_Mobile App #118.xlsx](https://github.com/TNGSB/eWallet/files/596819/Defect_Mobile.App.118.xlsx)

Defect Description : System displayed page full of code for FPX
Test Description : To verify the navigation from FPX select amount page to FPX Summary of transaction page

Refer the attachment for POT.

**Comment by mayyeap** [comment]
fix, please test again

**Comment by farahmohamad** [comment]
Retested and closed.

Refer attachment for POT
[Defect_Mobile App #118 - retest.xlsx](https://github.com/TNGSB/eWallet/files/602571/Defect_Mobile.App.118.-.retest.xlsx)
