### ISSUE TITLE
eWallet_MobileApp-Reload via Credit Card / Debit Card (Live Env) #119

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#146]
[Defect_Mobile App #119.xlsx](https://github.com/TNGSB/eWallet/files/596821/Defect_Mobile.App.119.xlsx)

Defect Description : System displayed page full of code for Credit Card / Debit Card
Test Description : To verify the navigation from Credit Card / Debit Card  select amount page to Credit Card / Debit Card  Summary of transaction page

Refer the attachment for POT.

**Comment by mayyeap** [comment]
fix, please check again

**Comment by farahmohamad** [comment]
Retested and closed.

Refer attachment for POT
[Defect_Mobile App #119 - retest.xlsx](https://github.com/TNGSB/eWallet/files/602556/Defect_Mobile.App.119.-.retest.xlsx)
