### ISSUE TITLE
eWallet_WebAdmin (User Admin) - Add User #31

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#15]
System does not validate Name field which should only for alphanumeric instead of special character

[Defect_BackOffice_01.xlsx](https://github.com/TNGSB/eWallet/files/568491/Defect_BackOffice_01.xlsx)

**Comment by mayyeap** [comment]
can you explain more on this?

**Comment by mayyeap** [comment]
reply as same as defect 1

**Comment by JasonABL** [comment]
Confirmed with TNG, Name can accept special character.
