### ISSUE TITLE
eWallet_FinancialReports_No header available in the Transaction History Report # Live_027

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#153]
Why there is no Header in the Transaction History report, to show the Account Details, such as Name, Account Number or ID, Date & Time report is generated, Report generated from which date to which date, and any other significant info to show this report belongs to who and which account.
- I believe users may need this details for their reference and may need to use this to submit claims, without these details, it is going to be difficult to justify & clarify

**Comment by JasonABL** [comment]
Have raised this to operation team, pending format from them.

Regards,
Jason

**Comment by ArjunLokanath** [comment]
Noted Jason, Please keep us posted once this is fixed.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
<Mark 16.12.16>  Fixed, retested and closed.
