### ISSUE TITLE
eWallet_FinancialReports_In the Transaction History email the Date & Time format needs to be updated to the standard Malaysian format # Live_028

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#154]
The Date & Time Format is using ddmmyyyy HH:MM:SS – Shouldn’t we be using standard Malaysian format for businesses, such as 07/11/2016 or 7 Nov 2016, and 11:04:45 AM/PM?

**Comment by JasonABL** [comment]
Hi,

Maybe we need Bavani advise if we need to change this. 

Regards,
Jason

**Comment by BavaniS** [comment]
ops team will give the template

**Comment by markshermanp** [comment]
<Mark 16.12.16>  Fixed, retested and closed.
