### ISSUE TITLE
eWallet_FinancialReports_In the Transaction History - The Description provided is not user friendly as it is showing Constants/Codes from the app and no details of the transaction for user to verify # Live_029

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#155]
Description - The Description provided is not user friendly as it is showing Constants/Codes from the app and no details of the transaction for us to verify.
- I believe we need to translate those codes into a more meaningful message to the users & provide more details for it
Example :
a)      PREPAID_RECEIVEFROM IN_APP – this is actually referring to money Transferred In from Izwan (user don’t understand IN_APP and missing Sender ID or Name for us to verify where it comes from)
b)      PREPAID_TRANSFERTO IN_APP - – this is actually referring to money Transferred Out to Izwan (missing Receiver ID or Name for us to verify where it goes to)
c)       PREPAID_TOPUP IN_APP Maybank (Credit / Debit Card) – I believe we need to change the term Prepaid to E-Wallet & Topup to Reload (Prepaid Topup can be referring to Ait Time topup)

**Comment by JasonABL** [comment]
Kindly check with Bavani if this need to be changed. Thanks.

Regards,
Jason

**Comment by ArjunLokanath** [comment]
Hi May,

Kindly advise on the below, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by mayyeap** [comment]
Hi Arjun, 

As Jason mentioned, please check with Bavani instead me. 

Thanks

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Kindly advise on the below issue as well, Thanks a lot

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
i will give ops team to come with generic name and resend to jason

**Comment by markshermanp** [comment]
<Mark 16.12.16>  Fixed, retested and closed.
