### ISSUE TITLE
eWallet_FinancialReports_In the Transaction History - User suggests to use better terminology for the columns in the Transaction History # Live_030

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#156]
The term used in the column is misleading – Expenditure & Income (Need to change to something else that is more meaningful)

**Comment by JasonABL** [comment]
Kindly check with Bavani and operation team what to replace with to be more meaningful. Thanks.

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Kindly advise on the below issue.. Thanks a lot

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
ops team will give the template

**Comment by markshermanp** [comment]
<Mark 16.12.16>  Fixed, retested and closed.
