### ISSUE TITLE
eWallet_Financial Reports_Under the Transaction History - User suggests to show the Closing Balance after each transaction # Live_031

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#157]
Is it possible for the report to include another column to show the After Balance for each of the transaction? This will help a lot in tracking the users reload & usage.

**Comment by JasonABL** [comment]
Can we compile everything in one issue? get requirement from Bavani and operation team, then we'll do the changes.

**Comment by ArjunLokanath** [comment]
Keeping Bavani in the loop, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
ops team will give the template

**Comment by markshermanp** [comment]
<Mark 16.12.16> New column added, however it shows the Before Balance and Not After. Reopening defect. @JasonABL please check

**Comment by markshermanp** [comment]
Fixed, retested and closed.
