### ISSUE TITLE
eWallet_FinancialReports_Under the Transaction History report - The User suggests to have the transactions sorted in Ascending order meaning to start from Old transactions to New transactions # Live_032

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#158]
Why is the report sorted in Descending Order? If this is a report generated and emailed to users, I believe it should be in Ascending Order (from old transactions to new transactions).

**Comment by JasonABL** [comment]
Can we compile everything in one issue? get requirement from Bavani and operation team, then we'll do the changes.

**Comment by ArjunLokanath** [comment]
No Jason, Tracking each issue - It's fix, Retest and Closure will become
very difficult and the defect needs to be kept open until all the
underlying issues are fixed. Hence it is best practice to track each issue
separately.. Thanks for your understanding

Hi Bavani,

Kindly advise on the below, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
ops team will give the template

**Comment by markshermanp** [comment]
<Mark 16.12.16>  Fixed, retested and closed (following Ops template)
