### ISSUE TITLE
eWallet_MobileApp_The Start Date and End Date by default is blank in the History section # Live_033

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#159]
The Start Date and End Date by default is blank.
I would suggest that the Start Date & End Date is defaulted to current date & auto load the transaction for current day or find other ways to make this better.

**Comment by mayyeap** [comment]
bavani please advise

**Comment by BavaniS** [comment]
initial plan to display by per day, 3 days 7 days. internal tng will look into this as part of ui/ux improvement.

**Comment by ArjunLokanath** [comment]
Noted and will update the defect accordingly before closing it, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
