### ISSUE TITLE
eWallet_MobileApp_Android (Registration)_03112016

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#16]
[Defect_Mobile App 03112016 #01.xlsx](https://github.com/TNGSB/eWallet/files/568553/Defect_Mobile.App.03112016.01.xlsx)

Test Description : To scroll and view the T&C
Expected Result : User should be able to scroll and view the T&C content
Actual Result : Unable to scroll and view the T&C content

Attached document for your perusal

**Comment by mayyeap** [comment]
develop

**Comment by BavaniS** [comment]
to be part of next build
