### ISSUE TITLE
eWallet_MobileApp_Mismatch between the date format in the Header & the date format in the transaction and also User suggests to use 12 hour time format # Live_034

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#160]
The Date format in the header is showing yyyy-mm-dd, and the transaction is showing yyyy/mm/dd HH:MM:SS – Shouldn’t we standardize the date such as either 07/11/2016 or 07-11-2016 or 7 Nov 2016, and time to 11:04:45 AM/PM (using a 12 hour format instead of 24 hours format)?

**Comment by mayyeap** [comment]
bavani please advise

**Comment by BavaniS** [comment]
ui/ux change

**Comment by ArjunLokanath** [comment]
Noted and closing this as well since it will be a part of the upcoming UI/
UX change, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
