### ISSUE TITLE
eWallet_MobileApp_Correct email address being displayed on the History page only after the User clicks on the checkbox and not being displayed by default when the page loads # Live_035

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#161]
The History page is showing "yourEmail@example.com" by default. It only changes to the correct email address when we tick either one of the checkbox below the page.
Can we immediately show the correct email address loaded by default in this page?

**Comment by mayyeap** [comment]
bavani please advise.

**Comment by mayyeap** [comment]
fix,please test in new build. the flow will be user tick only email appear. will standardized in ios and android

**Comment by ArjunLokanath** [comment]
OK Noted May, Thanks

Hi Farah,

Please help to retest this in the new build, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
