### ISSUE TITLE
eWallet_MobileApp_Incorrect title - "Transfer" used for a payment being made at the Scan to Pay page # Live_036

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#162]
The title shows "Transfer to Pie Kingdom".
Is the term "Transfer" correctly used here? Isn't this referring to Payment because Transfer is for Buddy?

**Comment by mayyeap** [comment]
Bavani, 

Please advise.

Thanks

**Comment by BavaniS** [comment]
may - malya will give you this.

arjun - close with note to be updated as part of ui/ux change

**Comment by ArjunLokanath** [comment]
Noted and closing this as advised, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
