### ISSUE TITLE
eWallet_MobileApp_In the 'Scan to Pay' module the Confirm or Proceed button to make the payment has been hidden behind the Keypad # Live_037

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#163]
After key-in the amount to pay, the button to confirm/proceed payment is behind the keyboard. User does not realize what to do until they swipe down to clear the keyboard. The button must be made visible for users at all times (not behind the keyboard).

**Comment by mayyeap** [comment]
Hi Arjun, 

this case been raise before, we are putting in ui change

**Comment by ArjunLokanath** [comment]
OK noted, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
As advised by Bavani all those UI changes related issues to be retested in March when available, Hence closing this defect now
