### ISSUE TITLE
eWallet_MobileApp_Scan to Pay - User comments that the Merchant confirmation via sms not reliable always # Live_038

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#164]
I can see the Merchant is a bit cautious on receiving the sms to confirm on the payment made by us. 
Is there a possibility that the sms is delayed or merchant does not receive it?
What is the proof to show to merchant that we have paid using the wallet?
Will they accept it if we show our transaction history?

**Comment by mayyeap** [comment]
Hi Bavani, 

Please advise.

**Comment by BavaniS** [comment]
subjective question. already informed payment business unit.

**Comment by ArjunLokanath** [comment]
Noted Bavani, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
