### ISSUE TITLE
eWallet_MobileApp_On the Transfer Page the User highlights an issue with the headers being displayed # Live_039

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#165]
I can see the header shown as "I" for "Izwan", but "#" for "mohd radzi". Why it shows the "#" character?

**Comment by mayyeap** [comment]
can you ask user to print screen? give account details

**Comment by ArjunLokanath** [comment]
Hi May,

This was raised by the FUT User - Zaly, Thanks

Hi Bavani,

Can you please help to loop in Zaly in this email so he can provide the
screenshots to May, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
zaly will send the screenshot

**Comment by mayyeap** [comment]
![426e65a3-0ef4-45bd-b697-aa256d9c8d4b](https://cloud.githubusercontent.com/assets/23113169/20592772/60ea6fd6-b26a-11e6-8bd1-bb8f60336006.jpg)

**Comment by mayyeap** [comment]
this happen because user enter space before entering there name.

**Comment by ArjunLokanath** [comment]
OK Understand and closing this defect now based on the explanation
provided, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
