### ISSUE TITLE
eWallet_MobileApp_User highlights that the Application is taking a long time to load the page for making payment using Credit card # Live_040

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#166]
It took >1 minute to load the Credit Card page using Level 5 Wi-fi (at 12:25PM)

**Comment by mayyeap** [comment]
Hi Bavani, 

Please raise this issue to ipay

**Comment by BavaniS** [comment]
test again today if ok.
i need few similar incident reported before escalating to ipay.

**Comment by ArjunLokanath** [comment]
Hi Farah/ Zharfan,

Can you help to make a couple of Credit card transactions today and let us
know if there is any slowness in loading the page for making the payment
using the Credit card, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
