### ISSUE TITLE
eWallet_MobileApp-Transaction History #126 

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#167]
Defect Description : The transaction history description are not user friendly. Information not displaying as per transaction history in mobile app

Test Description : To verify the transaction history description

UserID : Annemhd1710

Refer the attached POT for your perusal.

[Defect_Mobile App #126.xlsx](https://github.com/TNGSB/eWallet/files/605450/Defect_Mobile.App.126.xlsx)

**Comment by markshermanp** [comment]
@JasonABL pls advise on this

**Comment by markshermanp** [comment]
<Mark 16.12.16> fixed. Specs according to Ops template, closing defect
