### ISSUE TITLE
eWallet_MobileApp-Transaction History #127

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#168]
Defect Description : The unsuccessful / failed transaction displayed in the transaction history statement and there are no indicator for successful nor unsuccessful transaction history

Test Description : To verify the successful and unsuccessful transactions in the transaction history statement

User ID : Annemhd1710

Refer the attached POT for your perusal.

[Defect_Mobile App #127.xlsx](https://github.com/TNGSB/eWallet/files/605451/Defect_Mobile.App.127.xlsx)

**Comment by markshermanp** [comment]
@JasonABL pls advise on this

**Comment by markshermanp** [comment]
<Mark 16.12.16> ABL added new column 'Status'. Completed/successful txn are tagged as 'Finalized'. Defect closed.
