### ISSUE TITLE
eWallet_MobileApp-Transaction History(Live Env) #128

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#169]
[Defect_Mobile App #128.xlsx](https://github.com/TNGSB/eWallet/files/605453/Defect_Mobile.App.128.xlsx)

Defect Description : Wrong reload description for issued bank. Supposed to be CIMB instead for Maybank
Test Description : To verify the reload description in transaction history
User ID : Annemhd1710

Refer the attached POT for your perusal.

**Comment by JasonABL** [comment]
The description is actually combination as following.
TxnType + TxnSource + MerchantName
The description shown maybank is because the merchant name saved as maybank (credit/debit card). Please advise what to input to the description to avoid this.

**Comment by farahmohamad** [comment]
Hi Jason,

I would suggest you to confirm with Bavani on the description input for the transaction history.
We will test according to the decision.

Thanks.

**Comment by BavaniS** [comment]
jason - please come speak to me on this

**Comment by markshermanp** [comment]
@JasonABL please update on this

**Comment by markshermanp** [comment]
<Mark 16.12.16> No longer a defect as there is requirement change (following Ops template). It shows transaction type instead of description.
