### ISSUE TITLE
eWallet_MobileApp(Registration)_03112016

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#17]
As for today testing, there are 3 defects found in registration module.

Kindly refer the attached defects document for your perusal.

[Serv 2-03112016.zip](https://github.com/TNGSB/eWallet/files/568565/Serv.2-03112016.zip)

**Comment by mayyeap** [comment]
defect 16 - fixing
defect 17-fixing

**Comment by mayyeap** [comment]
![cf9eb99f-e44f-4f4f-a067-29084b796a90](https://cloud.githubusercontent.com/assets/23113169/20453673/6fc16f7a-ae67-11e6-8717-eb89e41859b7.jpg)

**Comment by farahmohamad** [comment]
[Defect_Mobile App #015.xlsx](https://github.com/TNGSB/eWallet/files/618430/Defect_Mobile.App.015.xlsx)
Hi May,

Retested with build 38 and 46 as per instruction.

Refer attached POT for your reference.

Thanks
