### ISSUE TITLE
eWallet_MobileApp-Transaction History(Live Env) #129

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#170]
Defect Description : Transaction history displayed blank value for "Expenditure" and "Income" field
Test Description : To verify the value for expenditure and income 
User ID : Annemhd1710

Refer the attached POT for your perusal.

[Defect_Mobile App #129.xlsx](https://github.com/TNGSB/eWallet/files/605461/Defect_Mobile.App.129.xlsx)

**Comment by markshermanp** [comment]
@JasonABL pls advise on this

**Comment by markshermanp** [comment]
<Mark 16.12.16> Transaction History screen have requirement changes, Defect no longer applicable.
