### ISSUE TITLE
eWallet_MobileApp-Profile Update(Live Env) #130

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#171]
Defect Description : There are no message displayed in user "My inbox". Previous messages in "My inbox" are not displayed when user uninstall the application and reinstall it

Test Description : To verify "My inbox" for previous transaction

User ID : Annemhd1710

Refer the attached POT for your perusal.
[Defect_Mobile App #130.xlsx](https://github.com/TNGSB/eWallet/files/605640/Defect_Mobile.App.130.xlsx)

**Comment by mayyeap** [comment]
As mentioned, the inbox  message are keep in mobile cache only. When you uninstall the app, cache will be deleted or you login to other phone, cache is captured in previous phone. This already agreed with Mr Zakri in previous meeting few month back.

**Comment by ArjunLokanath** [comment]
Dear Bavani,

Please see the message above from May and kindly help to provide direction on this defect, Can we close this now or will there a fix for this? Kindly advise, Thanks

**Comment by BavaniS** [comment]
arjun close this since she said agreed by my boss. i take it formally in future if any issue encountered.

**Comment by ArjunLokanath** [comment]
Noted Bavani and will close this defect, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
