### ISSUE TITLE
eWallet_MobileApp_User had to wait for more than 30 minutes after entering the MSOS code # Live_041

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#172]
After key-in MSOS Code using Level 5 Wi-Fi (on 10 Nov around 12:25PM), I am still not getting any reply on the bank page after waiting for >30 minutes. 
It is still showing "Processing your Maybank MasterCard Secure Code transaction. It may take a while, please wait. Thank you."
Is there any timeout set by the bank or our app here?
Please investigate what happens to this transaction. TQ.

**Comment by mayyeap** [comment]
Hi Bavani, 

Please check with IPay.

Arjun,
Please provide detail for checking. EXAMPLE: Login id and what kind of transaction user  is performing for investigation.

Thanks

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Can help to liaise with the FUT User (Zaly) for these details please as
this issue was identified by him, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
@BavaniS There is a session timeout set by each and every bank. However, this is a 3rd party issue. In which, it is out of touch n go control if there are no feedback from the bank. Mobile Application does not have timeout handling for this phase @mayyeap pls confirm
