### ISSUE TITLE
eWallet_MobileApp_The application only accepts the NRIC number when user enters it with the hyphens included in between # Live_042

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#173]
I entered my NRIC Number 721116145173, it says account does not exist. When I enter 721116-14-5173, then only it accepts it and prompts "your login ID has been sent to you registered..."

User do not know that they need to enter dashes. Why do we need to enter the dash? Is it because when we register we entered the dashes? User may not remember that they entered dashes during registraion.
Maybe we need to filter registration to not accept dash for MyKad, otherwise we will have different ID data format for MyKad.

**Comment by mayyeap** [comment]
We need to investigate this together with ABL.

Can give more data about user? login ID

**Comment by ArjunLokanath** [comment]
Hi May,

This was tested by the FUT user so not sure about the Login ID which was
used,

I guess you can try using your own Login ID and NRIC to register so you
should be able to view this issue, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by mayyeap** [comment]
Please get the detail, login id and screen shot for investigation

**Comment by BavaniS** [comment]
may
he saying we should allow only 999999887777 instead 999999-88-7777
can check with developer to allow alphanumeric a-z 0-9

**Comment by mayyeap** [comment]
yes already restric to alphanumberic. please check next build

**Comment by ArjunLokanath** [comment]
Noted May, Thanks

Hi Farah,

Please help to retest this on Monday when the new build is released, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
