### ISSUE TITLE
eWallet_MobileApp_Under the "Forgot Login ID" functionality the User receive the SMS only after 3 attempts # Live_043

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#174]
I only got the sms on my Login ID after 3 times trying this. 
I did not receive the sms for the first two actions.

**Comment by mayyeap** [comment]
SMS might delay.

Bavani,
Please explain to Arjun regarding sms delay.

Thanks

**Comment by BavaniS** [comment]
shortcode changed today, i will monitor and will ask to open new defect if happen again thereafter.

**Comment by ArjunLokanath** [comment]
Okay noted Bavani, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
