### ISSUE TITLE
eWallet_MobileApp-AirTime Top Up(Live Env) #131

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#175]
Defect Description : User did not receive any messages from service provider upon successful deduction at eWallet for AirTime top up RM5 and user mobile are not being reloaded accordingly.

Test Description : To verify the message send by selected service provider

User ID : Annemhd1710

Refer the attached POT for your perusal.
[Defect_Mobile App #131.xlsx](https://github.com/TNGSB/eWallet/files/605856/Defect_Mobile.App.131.xlsx)

**Comment by mayyeap** [comment]
![capture](https://cloud.githubusercontent.com/assets/23113169/20522437/42019e3a-b0eb-11e6-9aa8-0bb74ec67484.PNG)

**Comment by mayyeap** [comment]
Farah,

Please check with Arjun whether the top up success or it just delay as top up bar report stated success.
Is the number top up correct?

**Comment by farahmohamad** [comment]
Hi May, 

The above number are correct.

I have retested yesterday and it was a successful airtime reload.
I figured the 3rd party did not send out the successful message upon successful reload.

Need your advice on this.

Thanks

**Comment by mayyeap** [comment]
![dda0090a-855b-42fb-893f-937435283923](https://cloud.githubusercontent.com/assets/23113169/20592740/2a723be6-b26a-11e6-9c8c-948e75c9efd0.jpg)

**Comment by mayyeap** [comment]
![2f3af139-a733-41f9-ade6-639995b0b64b](https://cloud.githubusercontent.com/assets/23113169/20592746/30466952-b26a-11e6-91bd-868fa1c99c3e.jpg)

**Comment by mayyeap** [comment]
sms received for certain telco. ssending sms or not is depend on telco services side.

**Comment by farahmohamad** [comment]
Hi May,

Alright noted, will close this defect accordingly.

Thank you.
