### ISSUE TITLE
eWallet_MobileApp_User suggests to have a Date & Time details to be mentioned in the 'My Inbox' list # Live_046

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#179]
Can we have the Date & Time in the My Inbox list? There are so many notifications in the list displaying the same thing (e.g. Fund Received, Wallet Reloaded), but no date & time information for us to differentiate it in the main page.

**Comment by mayyeap** [comment]
UI change in next phase.

Bavani please close this.

**Comment by BavaniS** [comment]
arjun, put under no run. i dont know when this next phase happening.

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Noted however we cannot park it under 'No Run' status currently without a
date for the next phase since the UAT Cycle 2 is targeted to complete by
the End of next week (Dec 02) and having any pending No run cases will not
allow us to meet the exit criteria to close UAT Cycle 2,

We can test it as part of UAT Cycle 3 or Regression phase if this build can
be released early and during any of these 2 phases, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
