### ISSUE TITLE
e-Wallet_WebAdmin 07112016

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#18]
As for today testing, there are 3 defects found in web admin module.
-Card Management
-Customer Service

Kindly refer the attached defects document for your perusal.

[Sev_2.zip](https://github.com/TNGSB/eWallet/files/574946/Sev_2.zip)

**Comment by JasonABL** [comment]
Defect_BackOffice_07112016_#01  - Would suggest free text. 
Defect_BackOffice_07112016_#02 - It's a mandate field but not unique.
Defect_BackOffice_07112016_#03 - Confirmed with TNG Name can accept special character.
