### ISSUE TITLE
eWallet_MobileApp_Any purchase made to the Merchant should trigger a SMS but there was no SMS received # Live_047

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#180]
This defect was raised and discussed at the Defects meeting held with the Users

**Comment by mayyeap** [comment]
there is only inbox notification. SMS notification already disable.

Bavani, 
Please close this.

**Comment by BavaniS** [comment]
Yes, no SMS for QR purchase, only inbox and trx history.

For e-comm, user will receive email from the merchant direct.

**Comment by ArjunLokanath** [comment]
Noted Bavani and will close this defect as per the clarification received,
Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
