### ISSUE TITLE
eWallet_MobileApp_The User finds the Reload transaction not User friendly as after entering the Confirm button, The user still has to go to an external portal (MyClear) to complete the reload transaction # Live_048

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#181]
This defect was raised and discussed at the Defects meeting held with the Users

**Comment by mayyeap** [comment]
Bavani, 

Please advise as we will direct to extenal party page when we perform reload

**Comment by BavaniS** [comment]
what is this? explain further please.

**Comment by ArjunLokanath** [comment]
Hi Bavani,

This is when User was trying to perform a Reload transaction and after
confirming, They would be directed to the external MyClear website in order
to confirm again so that the transaction can be completed, This additional
step is what is bothering the Users and this was raised at the meeting with
the Users recently, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
