### ISSUE TITLE
eWallet_MobileApp-Utilities #133

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#182]
Defect Description : System displayed "I'm sorry, the program appears unusual, be about to exit" instead of displaying error message when there is incomplete information. User are automatically redirect to utilities home page

Test Description : To validate when only one field are left blank - amount left blank

User ID : Annemhd1710
[Defect_Mobile App #133.xlsx](https://github.com/TNGSB/eWallet/files/605931/Defect_Mobile.App.133.xlsx)

Refer the attached POT for your perusal.

**Comment by mayyeap** [comment]
fara, this is the error message from your phone, not the app.
"I'm sorry, the program appears unusual, be about to exit"

**Comment by mayyeap** [comment]
![30cb6a86-66e4-43cd-996a-f40f9f1c4882](https://cloud.githubusercontent.com/assets/23113169/20521538/a376bee8-b0e6-11e6-8f5f-724fe99fe4a6.jpg)

**Comment by farahmohamad** [comment]
Hi May,

I tested for Android version 6.0.1 Samsung Note 5, for IOS no issue.
In pay bills, it occurs for "Celcom" and "ASTRO" but not for UniFi.

Kindly check.

**Comment by mayyeap** [comment]
fix please test in new build

**Comment by farahmohamad** [comment]
Hi May,

I tested for Android version 6.0.1 Samsung Note 5 in build 38. 

Close this defect
Refer POT as attached.

[Defect_Mobile App #133-retest.xlsx](https://github.com/TNGSB/eWallet/files/618061/Defect_Mobile.App.133-retest.xlsx)
