### ISSUE TITLE
eWallet_MobileApp-Utilities #134

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#183]
Suggest to display currency indicator (RM or MYR) at the amount field.
 
![screenshot_20161122-165047](https://cloud.githubusercontent.com/assets/23113211/20518029/9ed46e7a-b0d8-11e6-938c-088bd1972506.png)

**Comment by mayyeap** [comment]
Bavani please advise on this.

**Comment by BavaniS** [comment]
suppose to show RM

**Comment by mayyeap** [comment]
This will change in next UI

**Comment by farahmohamad** [comment]
Will retest once the build is ready.
