### ISSUE TITLE
eWallet_MobileApp_The Reload Transaction Details and Confirm/ Back buttons does not fit into a single screen window # Live_049

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#184]
This defect was raised and discussed at the Defects meeting held with the Users

**Comment by mayyeap** [comment]
Can you print screen or elaborate more,. dont understand

**Comment by ArjunLokanath** [comment]
Hi May,

As per the User testing - The Confirmation screen for Reload transaction
does not have all the details and Confirm / Back buttons fitting into a
single window and the User needs to scroll to confirm the transaction or to
go back to the previous page,

Hope this clarifies.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
As per email from Bavani dated 2-Dec-16: Cosmetic defect, new ui/ux will take place. Close the issue.
