### ISSUE TITLE
eWallet_FinancialReports_Manual adjustments being required on the Reconciliations for every reload done on either MBB, FPX or JOMPAY # Live_050

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#185]
This defect was raised and discussed at the Defects meeting held with the Users

**Comment by markshermanp** [comment]
Kindly raise as clarification to TNG  @BavaniS

**Comment by BavaniS** [comment]
mark, lets discuss

**Comment by markshermanp** [comment]
Closing defect as business will look into the process of reconciliation/adjustments for FPX. If eWallet system fails the txn but 3rd party txn is successful, adjustment will be done manually.
