### ISSUE TITLE
eWallet_MobileApp_Reversal for a prepaid Top Up done on a Postpaid mobile number is not being done # Live_051

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#186]
This defect was raised and discussed at the Defects meeting held with the Users

**Comment by JasonABL** [comment]
Hi,

we need more info on this issue.

**Comment by markshermanp** [comment]
As per email from Bavani 2-Dec-2016: Reversal API given by ABL and integrated to Apac, close this issue. 

Exceptional Handling for other refund type (e.g. no response to user after 24 hours) is outside the system and to be handled by TNG ops team manually.
