### ISSUE TITLE
eWallet_MobileApp-Home page #135

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#187]
Defect Description : At My cards page, My devices page and my reward page, user to tap on the page and virtual keyboard pop out. 

Expectation : Should not pop out the virtual keyboard as the page are not suppose to be clickable by user.

Refer attachment,
![screenshot_20161122-173107](https://cloud.githubusercontent.com/assets/23113211/20518347/d5303f84-b0d9-11e6-9ba3-b8afe42a8261.png)
![screenshot_20161122-173110](https://cloud.githubusercontent.com/assets/23113211/20518346/d52d332a-b0d9-11e6-9d46-d7c1e8f0d309.png)

**Comment by mayyeap** [comment]
Fara,please try on your mobile too. i have tried mine, dont have the keyboard pop out. Please report tester mobile model for checking.

thanks

**Comment by farahmohamad** [comment]
Hi May,

I have tested with the new build and with Andoid version 6.0.1 Samsung Note 5.
For IOS no issue

**Comment by mayyeap** [comment]
fix, please test in next build

**Comment by farahmohamad** [comment]
Tested successfully.

However the my cards page are removed from the tested build 38 for android.

Therefore, close this defect.

Refer POT as attached.

![screenshot_20161128-171806](https://cloud.githubusercontent.com/assets/23113211/20662600/fa900a0c-b58e-11e6-8bff-6656f39825e0.png)

Thank you.
