### ISSUE TITLE
eWallet_MobileApp-INFO (Email Us) #136

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#189]
Defect Description : User to click the touch n go careline email and system displayed the virtual keyboard overlay.

Refer attachment.
![screenshot_20161122-173538](https://cloud.githubusercontent.com/assets/23113211/20518543/80cff672-b0da-11e6-9110-d18dd4909da3.png)
![screenshot_20161122-173541](https://cloud.githubusercontent.com/assets/23113211/20518544/80d27406-b0da-11e6-8ebd-765bec6af27e.png)

**Comment by mayyeap** [comment]
This is just a display. will took off the keyboard.

**Comment by mayyeap** [comment]
Farah, can you advise which version ios or android? which mobile model.
As we check from our side, we dont have this issue.

Thanks

**Comment by farahmohamad** [comment]
Hi May,

This is android version 6.0.1, samsung Note 5

Thanks

**Comment by mayyeap** [comment]
fix, please test in next build

**Comment by farahmohamad** [comment]
Retested and close this defect.

Refer POT as attached.

Tested with : -

i) Android - Samsung Note 5
ii) Build 38
![screenshot_20161128-171319](https://cloud.githubusercontent.com/assets/23113211/20662469/759617c4-b58e-11e6-95c8-d040ce49ae38.png)
