### ISSUE TITLE
e-Wallet_Mobile App (Registration-No OTP received) #142

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#194]
Hi All,

In order to retest #56 , user try to create a new user ID and went through the registration flow.
However, at "PIN Setup" page, requested OTP failed. User waited more than 5 minutes but no OTP received.

Mobile No : 0193187038
Service Provider : Celcom
Time Stamp : 07/12/2016 10:14 am

**Comment by markshermanp** [comment]
This is a known issue where it looks like we have an unstable sms gateway. @BavaniS every now and then we are encountering this issue (intermittent problem); on some days it is working fine, please advise

**Comment by BavaniS** [comment]
I already inform to close the issue last week
