### ISSUE TITLE
e-Wallet_MerchantPortal (Outlet)_07122016 #141

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#195]
Test Description : To verify on the values and system validation on mandatory input on search functionality
Expected Result : System displayed the existing records as per in the system

Actual Result : System displayed "No results found"

Steps: User to insert any input (all small letter) to mandatory fields in Outlet Name field and proceed the search process by clicking on the "Search" button

Refer attachment for reference
[Defect_MerchantPortal_#141.xlsx](https://github.com/TNGSB/eWallet/files/635869/Defect_MerchantPortal_.141.xlsx)

**Comment by JasonABL** [comment]
Currently all the search functions in the web portal are case sensitive.

**Comment by markshermanp** [comment]
@BavaniS need your input on this. Our recommendation is search function should not be case-sensitive; otherwise user need to input an exact match.
