### ISSUE TITLE
e-Wallet_Mobile App (Transaction-History) 06122016 #143

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#196]
**_Hi May,_**

Yesterday Bavani and TNG user has encountered a defect at transaction history.
When selected "Today's" date, error message "Invalid end date" was prompt. 

Same error message was prompt when user tried to select other date for "End date".
This is considered a show stopper to view transaction history.

Note: user try to view the transaction history for 30 days of transaction made.
Only occurred with Android. IOS works fine.

Tested in build 38 (live env android)

Thank you.

Attached POT for your reference.

![image](https://cloud.githubusercontent.com/assets/23113211/20960342/ea25692e-bc9a-11e6-92b0-ec09468be621.png)

**Comment by mayyeap** [comment]
Please close this as this is fix in build 39 android

**Comment by markshermanp** [comment]
retested OK. defect closed.
