### ISSUE TITLE
e-Wallet_Mobile App (Manual Reload-FPX) 08122016 #144

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#197]
**Hi All,**

No checkbox in FPX T&G page for IOS.

Follow up email from Ipay as below : - 
![image](https://cloud.githubusercontent.com/assets/23113211/21004347/d1f5292c-bd6a-11e6-97e3-10818b75ea5e.png)

**Comment by BavaniS** [comment]
ipay deployment next thursday, 22 dec

check after that

**Comment by farahmohamad** [comment]
Hi Bavani,

Will retest omce it is deployed.

Thank you.

**Comment by farahmohamad** [comment]
Hi All,

Tested with IOS build 13 UAT.

Attached the screenshot for POT.

Therefore, close the defect.

![image](https://cloud.githubusercontent.com/assets/23113211/22013268/22232818-dcd3-11e6-925f-3f5baa2df3e9.png)
