### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Vouchers Details Page) 15122016 #145

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#198]
Defect Description : Content in Voucher Details page overlapped with "Go to website" link. User having difficulties to click on the website link
UserID : TNG001
Device Used : Android (Nexus & Xiaomi)

Kindly refer the screenshot for POT.

Thank you
![content overlap](https://cloud.githubusercontent.com/assets/23113211/21216594/9afd41d4-c2e2-11e6-96a0-83e26bc01d74.jpg)

**Comment by mayyeap** [comment]
already raise this issue to TNG, waiting serena to feedback as she mentioned only time show without the word business hour. Already informed her that advise to key in not more than 20 character. waiting for her feedback

**Comment by mayyeap** [comment]
Farah, you may closed the case, as Joey (TNG) already limit the length to 20 character in the system as cc-ed in your email.

**Comment by farahmohamad** [comment]
Hi Jason,

Based on May's comment, need your help to set the param for "Additional Information" during campaign / offer creation.

Thanks.

Note : this is development environment

**Comment by JasonABL** [comment]
fixed, kindly retry

**Comment by farahmohamad** [comment]
Hi Jason,

Kindly confirm where can I find the "Additional Information" field?
Thanks.

**Comment by JasonABL** [comment]
Campaign creation page

**Comment by farahmohamad** [comment]
Tested with new voucher / campaign creation and the additional information are added accordingly via web portal.

The changes was verified with mobile application.
Therefore close the defect.

Tested with development application and passed.

![image](https://cloud.githubusercontent.com/assets/23113211/21793860/1a570efe-d730-11e6-86bb-a7059f0f01db.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21793866/200b7920-d730-11e6-9db9-9a49218ec168.png)
