### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Vouchers Details Page T&C column) 15122016 #146

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#199]
Defect Description : Content in Vouchers Details page, T&C column displayed in mobile Application. Mobile application unable to handle special char (e. G.  '  "  / )
Device : All androids and IOS

Refer the attached POT for reference.
![special characters displayed](https://cloud.githubusercontent.com/assets/23113211/21216678/221be382-c2e3-11e6-8f15-7626e9294b53.jpeg)

**Comment by mayyeap** [comment]
farah, have you check with ABL that the wording is correct or it show special character in the portal?

**Comment by JasonABL** [comment]
Fixed, Kindly retry.

**Comment by farahmohamad** [comment]
**Hi Jason,**

Tested and close the defect for T&C.
T&C content displayed as per set up in merchant portal.
