### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Use Vouchers) 15122016 #147

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#200]
Defect Description : After clicking "Use Now", the countdown counter page are displayed. The time format are not standardize. Standardize the time format using MM:SS,  not special char '  "
Tested on Device : both android and ios

Kindly refer the attached POT for your reference.
![countdown counter not standardize](https://cloud.githubusercontent.com/assets/23113211/21216790/b8e60c7a-c2e3-11e6-8aeb-19e76a9b7d13.jpg)

**Comment by mayyeap** [comment]
Need TNG advise on the UI.

**Comment by BavaniS** [comment]
Farah is correct, use minute and second, not ' or ''

**Comment by mayyeap** [comment]
Will changed in build 28th dec

**Comment by farahmohamad** [comment]
Tested with build 43 for android and build 53 for ios.

Refer the POT as attached.

![image](https://cloud.githubusercontent.com/assets/23113211/21756756/4c1298da-d660-11e6-891a-27e29ca57b4c.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21756757/51357ab2-d660-11e6-8d22-f778a13cba68.png)
