### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Use Vouchers) 15122016 #148

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#201]
Defect Description : No notification error that the voucher has expired. After 5mins expired,  can still use voucher

Device : Both Android and IOS
UserID : Tng001

Kindly refer the attached POT for your perusal
![no notification on expired session](https://cloud.githubusercontent.com/assets/23113211/21216849/0c65699a-c2e4-11e6-8f4a-7e8ef8089a90.jpg)

**Comment by mayyeap** [comment]
Hi Farah, 

after 5 mins, the voucher will close and pop out another success page, this already fix and release on end month build. IOS we tested is working fine. please test again

**Comment by mayyeap** [comment]
![image](https://cloud.githubusercontent.com/assets/23113169/21381940/0f24f92a-c799-11e6-9f41-3200ff48f1e5.png)

**Comment by farahmohamad** [comment]
Tested with build 43 for Android and 53 for IOS.
Refer attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/21757057/49fc3d04-d664-11e6-8e1d-1b1aa6205af8.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757059/4f14b870-d664-11e6-9b97-ff15828dc9ec.png)
