### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-My Vouchers Used/Expired Page) 15122016 #149

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#202]
Defect Description : Expired voucher shows as 'used',  incorrect tagging. It should be 'expired'
Device : Both android & IOS
UserID : TNG001

Kindly refer attached POT for your perusal.
![wrong tagging for used vouchers](https://cloud.githubusercontent.com/assets/23113211/21216929/7562c1e0-c2e4-11e6-83c4-55be9604f2a1.jpg)

**Comment by mayyeap** [comment]
Farah, please check with mark, this case consider closed.
Thanks

**Comment by markshermanp** [comment]
As discussed with Serena, no change required for now. Expired voucher (5 mins lapsed) will be considered used.
