### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-My Vouchers Used/Expired Page) 15122016 #150

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#203]
Defect Description : Clicking on the used or expired voucher does nothing,  unable to check the voucher details
Device : Both android & IOS
UserID : TNG001
![wrong tagging for used vouchers](https://cloud.githubusercontent.com/assets/23113211/21217006/dba46f08-c2e4-11e6-9ca7-45b9eb9bfb51.jpg)

Kindly refer attached POT for your perusal.

**Comment by mayyeap** [comment]
TNG agreed with the voucher detail is no longer available and only show 10 vouchers that is used/expired. Please check with Serena regarding this

**Comment by farahmohamad** [comment]
As per email as attached, this defect is closed.

![image](https://cloud.githubusercontent.com/assets/23113211/21382961/5ac8b1dc-c79e-11e6-8307-7f37f05972b1.png)
