### ISSUE TITLE
e-Wallet_MerchantPortal (Voucher Used Details Report)_19122016 #152

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#205]
Test Description : To download the Voucher Summary Report
Expected Result : 1. Succesfully download the report in PDF format

Actual Result : System displayed Bad Credentials page

Steps: 1. User to click Export as PDF link of the report from the page

Refer attachment for reference
[Defect_MerchantPortal_#152.xlsx](https://github.com/TNGSB/eWallet/files/660449/Defect_MerchantPortal_.152.xlsx)

**Comment by markshermanp** [comment]
@JasonABL any update on this pls

**Comment by muhdzhrfn** [comment]
Fixed
