### ISSUE TITLE
e-Wallet_Mobile App (Category Health & Beauty- Voucher thumbnail displayed not as per setup in Merchant Portal) #154

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#207]
The voucher thumbnail displayed in category of "Health & Beauty" are not as per setup in Merchant Portal.

Kindly refer the attachment.
![whatsapp image 2016-12-20 at 1 31 23 pm 1](https://cloud.githubusercontent.com/assets/23113211/21339302/1cb7f442-c6b9-11e6-82de-bf699960bd0d.jpeg)
![whatsapp image 2016-12-20 at 1 31 23 pm](https://cloud.githubusercontent.com/assets/23113211/21339305/1fc918c8-c6b9-11e6-8045-708966a1e593.jpeg)
![merchant portal view offer](https://cloud.githubusercontent.com/assets/23113211/21339307/24fbea82-c6b9-11e6-8fcb-a8468d4fbf1a.JPG)

Tested with build 9 for android.
UserID : leeanne1710

**Comment by JasonABL** [comment]
Please check with APAC as they did not capture the correct picture. You may change the picture to see the result. The square picture also should used at my vouchers page.

**Comment by mayyeap** [comment]
im checking wit my developer, get back to you on this

**Comment by markshermanp** [comment]
@mayyeap any update?

**Comment by mayyeap** [comment]
Fixed please retest in new build.
www.pgyer.com/dev-ios
www.pgyer.com/dev-android

**Comment by farahmohamad** [comment]
Tested with build 43 Android and 53 IOS for development environment.

Refer attached screenshot for POT.

![kidzania 1](https://cloud.githubusercontent.com/assets/23113211/21756820/282d95ae-d661-11e6-96c8-bb38c84f2436.JPG)
![kidzania 2](https://cloud.githubusercontent.com/assets/23113211/21756821/2e1f8cd8-d661-11e6-8dbb-eead515eb88c.JPG)
![image](https://cloud.githubusercontent.com/assets/23113211/21756988/33270894-d663-11e6-9108-b564b5b9f57b.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21756985/2dfa61d6-d663-11e6-8bbf-72bd7a282b62.png)
