### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Voucher Detail Page) 21122016 #155

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#208]
Defect Description :  When user click "Share" icon, application displayed "Whatsapp, facebook and Twitter" as a medium to share. However, when user click on all the social network, The application not redirect user to selected link - for IOS only. Android working fine.

Test Description : To verify the navigation from Touch N Go to social network link - Facebook, Twitter , Whatsapp

Tested with IOS device, Iphone 6.

**Comment by markshermanp** [comment]
@mayyeap hi may, pls update status

**Comment by mayyeap** [comment]
hi mark issue fixed. please download www.pgyer.com/dev-ios to test
or www.pgyer.com/dev-android

**Comment by markshermanp** [comment]
Android is working fine. Will retest at Live env instead when Loyalty is ready (for IOS)

**Comment by farahmohamad** [comment]
Retested with IOS build 53, development environment.

Refer attached screenshot for POT.
![image](https://cloud.githubusercontent.com/assets/23113211/21757183/ee63c758-d665-11e6-9949-61b5286012fb.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757187/f23185a0-d665-11e6-9e1f-575423210081.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757188/f5688be2-d665-11e6-972d-39ccc3eab9ca.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757191/f935c53c-d665-11e6-9c22-a9d7715697c9.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757199/073eba4e-d666-11e6-849f-024efb1e7354.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21757202/0cdebd0a-d666-11e6-9392-768ab80b93d4.png)
