### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Loyalty Activation flow for existing user) 21122016 #156

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#209]
Defect Description : When user click at "My Reward" tab, user are navigated to "Loyalty First Time Activation" flow even tho previously user has made some redemption of the vouchers

Test Description : To verify "My reward" page for existing user which already made redemption

Note : 

1. User has uninstall the app previously. This scenario happen when user re-download and launch the application, by using the same userID and password.

2. Tested in build 9 for Android

**Comment by mayyeap** [comment]
Hi farah, 

There is no first time identified for loyalty, we will change the ui for next build as approved by serena. Build release end month.

**Comment by mayyeap** [comment]
![capture](https://cloud.githubusercontent.com/assets/23113169/21381777/381db656-c798-11e6-97e0-603d8a9ad9e6.PNG)

**Comment by mayyeap** [comment]
![capture](https://cloud.githubusercontent.com/assets/23113169/21381786/4551a8f0-c798-11e6-9a48-916afebaa966.PNG)

**Comment by farahmohamad** [comment]
Hi All,

As clarified by May, therefore this defect is retest and closed.

Thank you.

![image](https://cloud.githubusercontent.com/assets/23113211/21515757/5e496a1c-cd0d-11e6-9b30-4fc76ba0dbda.png)
