### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Search Voucher Error Message) 22122016 #157

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#210]
Defect Description : When user left the search field blank, system prompt wrong error message for IOS only
Test Description : To view and verify the error message - search voucher field are left blank

Tested with IOS build 8.
![7c74f8bc-35b5-4b48-a25d-22c624c2f3c1](https://cloud.githubusercontent.com/assets/23113211/21415146/7d2a087c-c841-11e6-9e12-8da81597ea8f.jpg)

**Comment by mayyeap** [comment]
ABL to change error message

**Comment by JasonABL** [comment]
Check with APAC why IOS and Android different.
Message to be changed at mobile?

**Comment by markshermanp** [comment]
@mayyeap hi May,reassigned to you

**Comment by mayyeap** [comment]
Fixed, please retest

**Comment by farahmohamad** [comment]
Tested with IOS build 53, development environment.

Refer attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/21757328/cff7105c-d667-11e6-86b2-f510c1c1c6a0.png)
