### ISSUE TITLE
e-Wallet_Mobile App (Loyalty-Activation Profile Update Points) 22122016 #158

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#211]
Test Description : To verify the new points after earning points from "Profile Update"
Defect Description : When user successfully updated profile for the first time, system to add points to user's wallet of 200 points upon successful update. However, the successful message displayed as "200 points earned" but the wallet displayed 500 points instead of 200 points.

Tested in build 8 for IOS and 9 for android. 
Refer POT as attached.

![1](https://cloud.githubusercontent.com/assets/23113211/21419190/17bc7ffe-c861-11e6-9033-aaf7a6c4839a.jpg)
![2](https://cloud.githubusercontent.com/assets/23113211/21419193/1a7b551c-c861-11e6-92d7-704af76eddd1.jpg)
![3](https://cloud.githubusercontent.com/assets/23113211/21419194/1c4f3656-c861-11e6-87d9-90673f42acc8.jpg)

**Comment by mayyeap** [comment]
Already change the error message in next build "Profile updated. Points will be credited to your account"

**Comment by farahmohamad** [comment]
Hi Jason,

I am unable to edit the current promotion from 500 to 200 points as the UI stated 200 points.
Need your help to check on Admin Portal side to allow to create new promotion with new points or edit current promotion with new points.

Therefore,assign back to you.

Thank you.

**Comment by JasonABL** [comment]
Hi Farah,

You can change the end date to expiry date, and deleted the promotion and recreate a new campaign with 200 points promotion.

**Comment by farahmohamad** [comment]
Hi Jason,

Performed the action accordingly and I am able to delete the current promotion and create a new promotion with 200 points.

The 200 points reflected according to the setup.
Therefore, close this defect.

Refer attachment for POT.
![after profile update](https://cloud.githubusercontent.com/assets/23113211/21793371/aa641be0-d72b-11e6-98d3-47027055d9af.jpg)
![before profile update](https://cloud.githubusercontent.com/assets/23113211/21793379/b2da7544-d72b-11e6-9b24-226f9ed3a6a8.jpg)
