### ISSUE TITLE
e-Wallet_Mobile App (Login - User account are not blocked due to failed attempt login) 22122016 #159

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#212]
Test Description : To validate account locked after 3 times of failed attempts to login
Defect Description : User able to login with a correct password / userID after failed attempts for more than 3 times. User account are not locked. Both IOS and android

Tested with build 9 for Android and 8 for IOS.

**Comment by JasonABL** [comment]
Fixed, kindly retry.

**Comment by markshermanp** [comment]
Email from Bavani:

Hi Xavier,

Let it be at default 5x. Message remain as is at the moment.

Hi Malya,

Can you check with merdeka for the below. Add the EXCEED_PIN_RETRY in the attached excel, this is not there.

Key in wrong pin up to 5x
From “Incorrect PIN. Try Again.” can it be changed to “Incorrect PIN. Your account will be blocked after 5 times unsuccessful attempts.”

After 5x of wrong PIN
Get user message for “EXCEED_PIN_RETRY”

**Comment by farahmohamad** [comment]
Tested with userID : chemat1015

User attempt more than 10X invalid login, but user ID are not blocked as user may login with correct password input.

Tested with IOS build 11
Tested with Android build 13

![image](https://cloud.githubusercontent.com/assets/23113211/21631405/d28dba1e-d275-11e6-94f9-cef8836379e7.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21631414/05f9f5c0-d276-11e6-9aaf-f303ab8fdd1c.png)

**Comment by farahmohamad** [comment]
Clarified the flow to get the correct error message with Jason.
Therefore to close this defect as user are blocked due to 3 times attempt invalid login.

Blocked user : Chemat1015 and Rozita0911
