### ISSUE TITLE
e-Wallet_Admin Portal Loyalty (Add Voucher Campaign)_22122016 #160

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#213]
Test Description : Add Voucher Campaign (Enter special characters in Code field)
Expected Result : Display error message “value must be alphanumeric”

Actual Result : System allow enter special character in Code field

Steps: 1. User to fill up all the mandatory field available with a valid values except "Code" field are enter     with special character.
       2. User to click "Next" button

Refer attachment for reference
[Defect_AdminPortal_#160.xlsx](https://github.com/TNGSB/eWallet/files/668314/Defect_AdminPortal_.160.xlsx)

**Comment by markshermanp** [comment]
@JasonABL update on this pls

**Comment by JasonABL** [comment]
Fixed, kindly retry.
