### ISSUE TITLE
e-Wallet_Mobile App (Profile Update-Wrong Error Message) 29122016 #03

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#217]
Defect Description 1 : At "change password", user to insert wrong old password and system displayed "Old password entered incorrectly" in previous build.  However, in UAT build, the error message was displayed as "Password do not match. Please enter correct password twice". This error message are referring to "New Password and Confirm Password", not the Old password error message.

Defect Description 2 :  At "change PIN", user to insert wrong old PIN and system displayed "Old PIN entered incorrectly" in previous build.  However, in UAT build, the error message was displayed as "PIN do not match. Please enter correct PIN twice". This error message are referring to "New PIN and Confirm PIN ", not the Old PIN error message.

Need confirmation, is there any changes on error message in UAT build?

**Comment by mayyeap** [comment]
Hi Farah, mobile unable to validate the old pin or old password is correct or not, need ABL to validate the PIN or password whether is correct or not, therefore need ABL to change the error messages for this scenario.

**Comment by mayyeap** [comment]
Hi Farah, 

Previously mobile validate the old password by format, mobile unable to check whether the old password is correct or wrong. when we limit the length and change the keyboard to avoid user to key in a wrong format , then we unable to validate the format anymore, so the error message show now is from ABL. we need ABL to change the error message to the correct one.

Same as pin.
Please ask ABL for advise.

Thanks

**Comment by JasonABL** [comment]
Defect Description 1 : At "change password", user to insert wrong old password and system displayed "Old password entered incorrectly" in previous build. However, in UAT build, the error message was displayed as "Password do not match. Please enter correct password twice". This error message are referring to "New Password and Confirm Password", not the Old password error message.

The message was requested to change by APAC, but the checking was only check if the Old password match. Therefore changes as below:
1. Backend response message will change to "Old password do not match".
2. Mobile should do the verification for both new password if matching. If not match, should prompt the message "Please enter correct password twice".


Defect Description 2 : At "change PIN", user to insert wrong old PIN and system displayed "Old PIN entered incorrectly" in previous build. However, in UAT build, the error message was displayed as "PIN do not match. Please enter correct PIN twice". This error message are referring to "New PIN and Confirm PIN ", not the Old PIN error message.

The message was requested to change by APAC, but the checking was only check if the Old password match. Therefore changes as below:
1. Backend response message will change to "Old PIN do not match".
2. Mobile should do the verification for both new PIN if matching. If not match, should prompt the message "Please enter correct PIN twice".

Have sent to Hakim and pending him to assign out the task.

**Comment by mayyeap** [comment]
Hi Farah, 
we already change from our side (mobile), you may test.

**Comment by JasonABL** [comment]
Resolve by Jason Tee
Mantis Closed by Hakim

**Comment by farahmohamad** [comment]
Hi All,

Tested with Android build 20 and please refer the attached screenshot for proof of testing.
The app return error message as per action made.

Therefore, close this defect.

Thank you.
![screenshot_20170117-125217](https://cloud.githubusercontent.com/assets/23113211/22008221/26bfafdc-dcb4-11e6-8955-4da4f0d36f7f.png)
![screenshot_20170117-125233](https://cloud.githubusercontent.com/assets/23113211/22008222/26c25d04-dcb4-11e6-9736-07b5ab5c84f7.png)
