### ISSUE TITLE
e-Wallet_Mobile App (Transaction History-Start Date & End Date) 04012017 #05

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#219]
Test Case Description : To view selected start date and end date
Defect Description : When user selected the start date from the drop down list, the selected date display are not as per selected date. Date change from (4 Jan 2017) to (4 April 2017)

Tested with : Android UAT Build 13 
UserID : Annemhd1710
Phone Model : Samsung Note 5

Refer attachment.

Defect only occurs for Android.

![image](https://cloud.githubusercontent.com/assets/23113211/21629588/c803304e-d264-11e6-8671-68ca8f4ac254.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21629594/cad344bc-d264-11e6-8051-10e783f87c69.png)

**Comment by mayyeap** [comment]
This is fixed too will reflect in next build.

**Comment by mayyeap** [comment]
Hi all, 

pls download the latest build in uat enviroment.
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Thanks

**Comment by farahmohamad** [comment]
Hi All,

Tested with android and IOS as below : -

ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

The date works fine and retest passed.
Therefore close the defect.

Attached the screenshot for POT.
![screenshot_20170117-121346](https://cloud.githubusercontent.com/assets/23113211/22007594/e021482e-dcae-11e6-8c15-f4e3e222d572.png)
![screenshot_20170117-121402](https://cloud.githubusercontent.com/assets/23113211/22007595/e02143f6-dcae-11e6-8a08-970a96072fea.png)

Thank you.
