### ISSUE TITLE
e-Wallet_Mobile App (Wallet Balance Incorrect-Sender Wallet after transfer) 04012017 #06

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#220]
Test Case Description : To view balance after successful transfer
Defect Description : User initial balance is RM0.12. When user made a successful transfer of RM0.05, the expected after balance is RM0.07. Instead, the balance displayed as RM0.70

Tested with : Android UAT Build 13
UserID : Annemhd1710
Phone Model : Samsung Note 5

Refer attachment.

![image](https://cloud.githubusercontent.com/assets/23113211/21629785/4936ac58-d266-11e6-88dc-acec7fce5c4f.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21629818/86546616-d266-11e6-9432-e661ed334094.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21629841/b956f6f0-d266-11e6-9504-294194a99ad1.png)

**Comment by mayyeap** [comment]
Hi Farah, 

This is fixed will reflect in new build.

Thanks

**Comment by mayyeap** [comment]
Hi Farah, 

Would you like to close this?

**Comment by farahmohamad** [comment]
Retest and closed.

![image](https://cloud.githubusercontent.com/assets/23113211/21761347/55e73960-d68d-11e6-9bb0-a654fa7d7aa3.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21761371/6a2e91ca-d68d-11e6-999f-c052c73fdc0c.png)

**Comment by farahmohamad** [comment]
Reopen the defect as the defect occurs during transfer transaction.
Tested with android, build 13.

Attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/21834286/f7c7b48c-d7ee-11e6-808c-456e7781a629.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21834290/fd8db222-d7ee-11e6-81ab-17ca7d2c0dbe.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21834328/4784ee54-d7ef-11e6-912d-73de48fba20c.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21834330/4c4ffeb0-d7ef-11e6-9eb1-53d725f7319c.png)

**Comment by mayyeap** [comment]
Hi all, 

pls download the latest build in uat enviroment.
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Thanks

**Comment by farahmohamad** [comment]
Hi All,

Tested with android and IOS as below : -

ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

The balance displayed as per amount deducted from wallet.
Therefore close the defect.

Attached the screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/22007674/9902557c-dcaf-11e6-8afd-ad14d1600dec.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22007683/ac519a5c-dcaf-11e6-87f0-f22dc710ea8b.png)

**Comment by farahmohamad** [comment]
![screenshot_20170117-121905 1](https://cloud.githubusercontent.com/assets/23113211/22007704/e8c3a9c6-dcaf-11e6-9975-17d505367915.png)
