### ISSUE TITLE
e-Wallet_Mobile App (Transaction History - End Date) 04012017 - Duplicate Error

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#221]
Test Case Description : To select end date of transaction history
Defect Description : User chose 14th December 2016 as start date and 4th Jan 2017 as end date. However, the system displayed as 4th April for end date.

Tested with : Android UAT Build 13
UserID : Annemhd1710
Phone Model : Samsung Note 5

Refer attachment.
![image](https://cloud.githubusercontent.com/assets/23113211/21630008/15bfff76-d268-11e6-8fe8-4b92d8a3758a.png)

**Comment by markshermanp** [comment]
Duplicate error. Closing defect
