### ISSUE TITLE
e-Wallet_Mobile App (Reload - FPX page displayed blank page) 04012017 #08

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#223]
Test Case Description : To verify the navigation from reload page to FPX page
Defect Description : After select amount to reload, user are redirect to blank FPX page for IOS and java script page for Android

Tested with : IOS build 11 and Android build 13
UserID : Annemohd17
Phone Model : Iphone 6 & Sansung Note 5

Refer attachment.

![image](https://cloud.githubusercontent.com/assets/23113211/21636574/2ed4f42c-d29e-11e6-958a-c27f99a02646.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21636594/41dcc112-d29e-11e6-9d1a-880e99bae47c.png)

**Comment by markshermanp** [comment]
Payment module is currently not ready. Logging this issue as we have dependency on the test execution.

**Comment by markshermanp** [comment]
From: Techsupport <techsupport@ipay88.com.my> 
Date: 13/01/2017 10:06 (GMT+08:00) 
To: Bavani Shanmugam <bavani@touchngo.com.my> 
Subject: Re: Re: FW: Reload fpx & credit card [#3331394] 

Below messages successfully sent to Chong LK, Grace Ng, Abdul Hakim Ismail, Bavani Shanmugam, Mohd Radzi Abdul Hamid 

Dear Bavani,

Good morning to you.
Just to update you on the status of yesterday issue.
Yesterday we had assisted APAC team to troubleshoot the issue and notice some mandatory field did not post value to ipay88 gateway thus ipay88 reject it. 
This had convey to APAC team and notice from transaction record they able reach to ipay88

**Comment by mayyeap** [comment]
Dear All, 

Ios fixed, android will release build on monday. please re test on monday

**Comment by mayyeap** [comment]
Hi all, 

pls download the latest build in uat enviroment.
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Thanks

**Comment by farahmohamad** [comment]
Hi all,

Retested with below build : -
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Attached screenshot is POT.
Therefore, close this defect.

![screenshot_20170117-105929](https://cloud.githubusercontent.com/assets/23113211/22008116/16cc3222-dcb3-11e6-8be4-5da120eabc31.png)
![screenshot_20170117-110409](https://cloud.githubusercontent.com/assets/23113211/22008117/16cdceac-dcb3-11e6-9b58-5ad93849456d.png)
![screenshot_20170117-110515](https://cloud.githubusercontent.com/assets/23113211/22008118/16ce9576-dcb3-11e6-81ad-0e1d1c324f15.png)
![screenshot_20170117-110543](https://cloud.githubusercontent.com/assets/23113211/22008119/16ceae62-dcb3-11e6-9411-529e588de3a3.png)
