### ISSUE TITLE
e-Wallet_Mobile App (Reload - Credit/Debit Card page displayed blank page) 04012017 #09

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#224]
Test Case Description : To verify the functionality and navigation of "linked Card" button
Defect Description : At Credit/ Debit card page ,user to click on the "linked Card" button to proceed to the next page which displayed as blank page for IOS and java script for android.

Tested with : IOS build 11 and Android build 13
UserID : Annemohd17
Phone Model : Iphone 6 & Sansung Note 5

Refer attachment.

![image](https://cloud.githubusercontent.com/assets/23113211/21636758/d1a4c57e-d29e-11e6-82c4-c94f6415e3f0.png)
![screenshot_20170104-165117 1](https://cloud.githubusercontent.com/assets/23113211/21636785/e7ede3f6-d29e-11e6-977b-9a9a8b26bd3c.png)

**Comment by markshermanp** [comment]
From: Techsupport <techsupport@ipay88.com.my> 
Date: 13/01/2017 10:06 (GMT+08:00) 
To: Bavani Shanmugam <bavani@touchngo.com.my> 
Subject: Re: Re: FW: Reload fpx & credit card [#3331394] 

Below messages successfully sent to Chong LK, Grace Ng, Abdul Hakim Ismail, Bavani Shanmugam, Mohd Radzi Abdul Hamid 

Dear Bavani,

Good morning to you.
Just to update you on the status of yesterday issue.
Yesterday we had assisted APAC team to troubleshoot the issue and notice some mandatory field did not post value to ipay88 gateway thus ipay88 reject it. 
This had convey to APAC team and notice from transaction record they able reach to ipay88

**Comment by mayyeap** [comment]
Hi All, 

ios fixed , android will release build on monday

**Comment by mayyeap** [comment]
Hi all, 

pls download the latest build in uat enviroment.
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Thanks

**Comment by farahmohamad** [comment]
Hi all,

Retested with below build : -
ios (build 13)-www.pgyer.com/uat-ios
android (build 20)-www.pgyer.com/uat-android

Attached screenshot is POT.
Therefore, close this defect.
![screenshot_20170117-111314](https://cloud.githubusercontent.com/assets/23113211/22008042/7754c862-dcb2-11e6-9f19-cbbf465a824c.png)
![screenshot_20170117-113645](https://cloud.githubusercontent.com/assets/23113211/22008043/77562b9e-dcb2-11e6-845e-95e87564a030.png)
![screenshot_20170117-113652](https://cloud.githubusercontent.com/assets/23113211/22008044/775caf6e-dcb2-11e6-8e13-155518ad233e.png)

Thanks
