### ISSUE TITLE
e-Wallet_Mobile App (Airtime Reload - Wrong error message) 04012017 #10

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#225]
Test Case Description : 
1) To verify the error message when user insert invalid PIN
2) To verify the error message when user has insufficient balance
3) To verify the error message when user duplicate a failed transaction
4) To verify the unsuccessful message upon unsuccessful transaction
5) To verify the successful message upon successful transaction

Defect Description : All the error message displayed as "null"

Tested with : IOS build 11
UserID : Annemohd17
Phone Model : Iphone 6 

Refer attachment.

![image](https://cloud.githubusercontent.com/assets/23113211/21636997/ee07e9a2-d29f-11e6-9583-bd13bcfe5f8a.png)

**Comment by markshermanp** [comment]
Payment module is currently not ready. Logging this issue as we have dependency on the test execution.

**Comment by mayyeap** [comment]
Hi Farah, 

This function is not ready yet. Developer still doing troubleshooting.

**Comment by mayyeap** [comment]
Hi Farah, 

Please retest and close this case.

**Comment by farahmohamad** [comment]
Retested the function in build 13 for Android and build 11 for IOS.

![screenshot_20170106-105001](https://cloud.githubusercontent.com/assets/23113211/21761061/7d56f17c-d68b-11e6-8706-9f801588f5ff.png)
![screenshot_20170106-105007](https://cloud.githubusercontent.com/assets/23113211/21761062/7d597b4a-d68b-11e6-93aa-c1f1f4f06df7.png)
![screenshot_20170106-105028](https://cloud.githubusercontent.com/assets/23113211/21761063/7d59d022-d68b-11e6-952e-971685e73d6a.png)
![screenshot_20170106-105119](https://cloud.githubusercontent.com/assets/23113211/21761084/a21756a0-d68b-11e6-9f9f-ca99ae0ba554.png)
