### ISSUE TITLE
e-Wallet_Mobile App (In App Purchase-Movie Tickets) 04012017 #11

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#226]
Test Case Description : To confirm on purchase by inserting a valid phone number
Defect Description : Confirm button are not clickable. Therefore unable to proceed to the next page.

Tested with : IOS build 11
UserID : Annemohd17
Phone Model : Iphone 6

Refer attachment.

![image](https://cloud.githubusercontent.com/assets/23113211/21637121/7e3af190-d2a0-11e6-81d5-557cdf81e01a.png)

**Comment by markshermanp** [comment]
Payment module is currently not ready. Logging this issue as we have dependency on the test execution.

**Comment by farahmohamad** [comment]
Checked with May and retested for IOS. 

May closed this defect as user need to select 2 seats if user select the "Twin pack" in confirmation page.
User may proceed with confirmation if user which to select "Adult standard" seat in confirmation page.
