### ISSUE TITLE
e-Wallet_Mobile App (OTP Request - System allowed expired OTP) 05012017 #13

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#227]
Test Case Description :

1. To verify the input of expired OTP - exceed 3 minutes after receiving the OTP
(for all functionality. example : forgot password, registration, forgot PIN)

Defect Description : When user requested the 1st OTP, OTP was send to user's mobile successfully. After 3 minutes, user requested 2nd OTP. After successfully received the 2nd OTP, user to input the 1st OTP (which supposedly expired), to proceed with action. However, system allowed user to proceed with the 1st OTP.

Defect description 2 : Another defect that user found is,user are allowed to click "Click to received OTP" even though user has requested for the 1st OTP and click back button, and click again to request 2nd OTP. By right the "Click to receive OTP" should not clickable as user has requested 1st OTP previously.
<this scenario are performed within 3 minutes>

Tested with : IOS build 11 & Android build 13
UserID : Annemohd17
Phone Model : Iphone 6 & Samsung Note 5

**Comment by mayyeap** [comment]
Apac will display the error messages as per hakim email.

**Comment by JasonABL** [comment]
Resolved and fixed by Jason Tee
Mantis Issue Closed by Hakim

**Comment by farahmohamad** [comment]
Hi All,

Tested with build 20 however the fixes have yet deployed by ABL.
Will retest once deployed.

Thanks.

**Comment by farahmohamad** [comment]
Hi All,

After ABL has successfully deployed, I have tested with build 21 for android and retested passed.

Refer attached screenshot for POT.

Therefore close the defect.
![screenshot_20170120-090012](https://cloud.githubusercontent.com/assets/23113211/22131848/26122a4e-def1-11e6-8776-eeb6a2dec245.png)
![screenshot_20170120-090258](https://cloud.githubusercontent.com/assets/23113211/22131854/2ce6d84c-def1-11e6-8c39-e117172a2369.png)
![screenshot_20170120-090308](https://cloud.githubusercontent.com/assets/23113211/22131851/2ce27be4-def1-11e6-9c0d-53cc87e2b473.png)
![screenshot_20170120-090311](https://cloud.githubusercontent.com/assets/23113211/22131850/2ce1e918-def1-11e6-9c9e-00bf99b8a7e2.png)
![screenshot_20170120-090315](https://cloud.githubusercontent.com/assets/23113211/22131853/2ce62d98-def1-11e6-8873-3f2251cbcb72.png)
![screenshot_20170120-090326](https://cloud.githubusercontent.com/assets/23113211/22131852/2ce369dc-def1-11e6-8da8-3c3b09dfc291.png)







Thanks.
