### ISSUE TITLE
e-Wallet_AdminPortal (Customer Service) 06012017 #14

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#228]
Test Description : Edit Customer (Edit Customer with the ID No has same data that already exist)
Expected Result : Display Error Message "Cannot add customer"

Actual Result : System display service not available as image below

Steps: 1. User to fill up all the ID No has same data that already exist
           2. User to click "Update" button

![image](https://cloud.githubusercontent.com/assets/23113210/21711611/bd68bb28-d42a-11e6-85f6-4364c85107ed.png)

**Comment by JasonABL** [comment]
Hi, 

Can i have the ID no which show this error?

**Comment by muhdzhrfn** [comment]
I edited the ID No for Login ID muhdzhrfn from 930420045143 to 921017146230, which data already exist for Login ID annemohd17

**Comment by muhdzhrfn** [comment]
Fixed and close it now

![image](https://cloud.githubusercontent.com/assets/23113210/21924468/4628909e-d9b4-11e6-9fab-cea533d530e2.png)
