### ISSUE TITLE
e-Wallet_Mobile App (AirTime-No error message) 06012017 #16

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#230]
Test Description : To verify error message when user insert an invalid phone number - less than 10 digit length

Defect Description : System allow less than 10 character input, no error message displayed

Tested with :  Android build 13
UserID : Annemohd17
Phone Model : Samsung Note 5

Refer attachment

![image](https://cloud.githubusercontent.com/assets/23113211/21712340/3fe21a00-d42f-11e6-9969-460f83c1cd02.png)

**Comment by mayyeap** [comment]
Hi Farah, there is no min limitation only max limitation, please close the case

**Comment by farahmohamad** [comment]
**Hi May,** 

For iOS, there is min length.
User entered less than 10, it does not allow to proceed with PIN page.

Please check,

![image](https://cloud.githubusercontent.com/assets/23113211/21761201/4a934cb2-d68c-11e6-8382-68840e00d321.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21761203/4dff7e98-d68c-11e6-9298-098ecc7709c2.png)

**Comment by mayyeap** [comment]
Hi Farah, 

There is no min rules given to us but to become a valid mobile number in malaysia the min digits is 10. 
We will standardized to min 10 digits for android

Thanks

you may close this case

**Comment by farahmohamad** [comment]
Hi All,

Tested with build 20 for android.
Attached is the screenshot as POT.
![screenshot_20170117-124830](https://cloud.githubusercontent.com/assets/23113211/22008159/8e88c708-dcb3-11e6-878f-c7d13605951c.png)
![screenshot_20170117-124832](https://cloud.githubusercontent.com/assets/23113211/22008160/8e896f50-dcb3-11e6-9995-bacfa298a212.png)
![screenshot_20170117-124839](https://cloud.githubusercontent.com/assets/23113211/22008161/8e8a698c-dcb3-11e6-88ca-7ec9cfce6599.png)

Therefore, close this defect.

Thank you.
