### ISSUE TITLE
e-Wallet_AdminPortal (Report - Web Admin - Reconciliation Management) 06012017 #17

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#231]
Test Description : View the updated TnG Report List
Expected Result : Display the details of the reports.

Actual Result : System only display the report until 11/12/2016 although the transaction has been made yesterday (05/01/2017)

![image](https://cloud.githubusercontent.com/assets/23113210/21712957/695e837a-d432-11e6-93c5-77ad7b9d88a6.png)

**Comment by JasonABL** [comment]
Have started the batch. Please try check again tmrw.

**Comment by muhdzhrfn** [comment]
Noted, will do the retest tomorrow (11/1/2017)
