### ISSUE TITLE
e-Wallet_Mobile App (e-Commerce transaction) 16012017 #18

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#233]
Transaction history for E-Commerce transaction displayed as "blank" in transaction detail page and transaction are verified in Admin Portal.

Tested with user details as below : - 

Build : 16 for Android
Environment : UAT
UserID : muhdzhrfn
Password : Za200493

Attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/21970235/636f63e4-dbdf-11e6-8216-afe6e609a05f.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21970272/b0818eb4-dbdf-11e6-8336-79e7fb79edbb.png)
![image](https://cloud.githubusercontent.com/assets/23113211/21970289/d1570b14-dbdf-11e6-9c32-6d9d829694ad.png)

**Comment by JasonABL** [comment]
If the remarks field , mobile may need to populate the details field with the merchant name in the response due to ecom transaction do not populate the remark field.

**Comment by mayyeap** [comment]
Hi Farah,

E-commerce transaction is like Jompay, transaction done outside the mobile app. Please seek abl assistance again.

**Comment by farahmohamad** [comment]
Hi All,

Tested with muhdzhrfn ID and the details populated both at transaction history.

Therefore, close the defect.

Attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/22139694/9c6c4ca2-df22-11e6-94ae-ff1830164d10.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22139701/a25f16bc-df22-11e6-889d-a86686ef36f0.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22139732/d5af2e3a-df22-11e6-8b79-0a190abb10d5.png)
