### ISSUE TITLE
e-Wallet_Mobile App (Scan & Pay) 17012017 #19

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#234]
Defect Description : User to perform "Insufficient Balance" scenario for merchant payment. However, upon successful scanning and PIN input, the application keep on loading with end up no result.

Tested with android build 20, UAT environment.

Attached screenshot for POT.

![screenshot_20170117-152954](https://cloud.githubusercontent.com/assets/23113211/22011603/f51a158c-dcca-11e6-8d2d-514e8a99b59e.png)
![screenshot_20170117-153415](https://cloud.githubusercontent.com/assets/23113211/22011604/f51c6e2c-dcca-11e6-8e48-8a72e60f0bf5.png)
![screenshot_20170117-153427](https://cloud.githubusercontent.com/assets/23113211/22011605/f51c97c6-dcca-11e6-82ed-572a36688a10.png)

**Comment by farahmohamad** [comment]
The test cases related : - 

UC8_Mobile_App_06
UC8_Mobile_App_07

**Comment by farahmohamad** [comment]
Tested with Android build 21, still not working.
Page keep on loading.

However, in transaction history displayed the transaction status is "failed"

![image](https://cloud.githubusercontent.com/assets/23113211/22048587/f4448f5e-dd68-11e6-8f21-b7a71c9a0263.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22048595/f9d25794-dd68-11e6-912e-f75222941e77.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22048600/fcd9af50-dd68-11e6-8d6f-49227da272cb.png)

**Comment by mayyeap** [comment]
Please test build 22 and close the case

**Comment by farahmohamad** [comment]
Hi All,

Retested with build 22 for Android and 17 for IOS, Live environment.
Therefore, close this defect.

Refer attached screenshot for POT.

Thank you.

![image](https://cloud.githubusercontent.com/assets/23113211/22189910/ac87e422-e15a-11e6-942b-95a40d06e272.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22189913/b187c4c4-e15a-11e6-94d1-7f9566e6f46a.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22189915/b7ecacc6-e15a-11e6-8372-e4be03aa5cc3.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22189917/bc483aba-e15a-11e6-9056-0b1cc2969572.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22189924/c61e02d6-e15a-11e6-89e9-2a2b253e8e88.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22189926/cb3f099a-e15a-11e6-883a-788419462288.png)
