### ISSUE TITLE
e-Wallet_Mobile App (My Inbox - Content) 17012017 #21

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#236]
All of the inbox content displayed "Merchant Reference No." as "Null".

Attached screenshot for POT.
![screenshot_20170117-155831](https://cloud.githubusercontent.com/assets/23113211/22012277/187a7ffa-dcce-11e6-82d2-7796fa535edf.png)
![screenshot_20170117-155945](https://cloud.githubusercontent.com/assets/23113211/22012276/187a5930-dcce-11e6-9ab8-b86892649806.png)
![screenshot_20170117-155951](https://cloud.githubusercontent.com/assets/23113211/22012279/187cdbd8-dcce-11e6-95dc-52ba352389ee.png)
![screenshot_20170117-155956](https://cloud.githubusercontent.com/assets/23113211/22012278/187cd2f0-dcce-11e6-8dd0-1cc6647b9a80.png)

**Comment by JasonABL** [comment]
Check with Apac why null?

**Comment by farahmohamad** [comment]
As per confirm with May from Apac, only payment teo merchant would have the merchant reference No.
Therefore, retested and close this defect.

![screenshot_20170118-101542](https://cloud.githubusercontent.com/assets/23113211/22053653/266166c8-dd8d-11e6-8865-e102aec17239.png)
![screenshot_20170118-105237](https://cloud.githubusercontent.com/assets/23113211/22053654/26657d4e-dd8d-11e6-82ca-dd6949f827b3.png)
![screenshot_20170118-105242](https://cloud.githubusercontent.com/assets/23113211/22053655/26876224-dd8d-11e6-9cf8-525de698c612.png)

**Comment by farahmohamad** [comment]
Tested with build 21 Android and 14 IOS
