### ISSUE TITLE
e-Wallet_MerchantPortal (Voucher Management) 17012017 #22

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#237]
Test Description :View List Offer(Voucher Campaign)
Expected Result : Display the details of the voucher campaign same as admin portal

Actual Result : System does not display the same list at the merchant portal compare to admin portal.

Steps: 1. Created a voucher campaign for the same merchant (TNG TEST) at admin portal for Premium        type. 
          2. Compare the list of voucher campaign from admin and merchant portal. 

![image](https://cloud.githubusercontent.com/assets/23113210/22012860/17413dec-dcd1-11e6-8dff-c910fa9ffd87.png)
There are 7 campaigns created

![image](https://cloud.githubusercontent.com/assets/23113210/22012888/367d5010-dcd1-11e6-8340-d38381825bc3.png)
There's only 6 campaigns listed at merchant portal

**Comment by muhdzhrfn** [comment]
![image](https://cloud.githubusercontent.com/assets/23113210/22013375/9f1a5d28-dcd3-11e6-8645-e374fc3b6a8f.png)
There's also 6 campaigns listed at Merchant Offer at admin portal, should be 7 campaigns.

**Comment by JasonABL** [comment]
Hi,

The reason is the offer is created by the the admin from admin portal. Will need to confirm again the business requirement, does the merchant need to see what the admin created from admin portal?

**Comment by markshermanp** [comment]
@JasonABL  By right it should display at my merchant portal since it is my offer that was created from the admin portal; otherwise I wouldn't be able to track the whole list of my offer because something is missing from my list. @BavaniS any comment?

**Comment by markshermanp** [comment]
Retest OK. Closed
