### ISSUE TITLE
e-Wallet_Mobile App (Reload FPX - Back button not functioning) 17012017 #23

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#238]
Defect Description : User to reload via FPX. When user is at 3rd party page and click "back" button, user not navigated to previous page. User remain at the same page.

Tested for IOS build 13 and Android build 20.

Refer attached screenshot for POT.
![image](https://cloud.githubusercontent.com/assets/23113211/22014104/2153329e-dcd7-11e6-8554-e43e222d095c.png)

**Comment by markshermanp** [comment]
As discussed with Bavani and May, this is coding limitation. Closing defect.
