### ISSUE TITLE
e-Wallet_Mobile App (FPX Reload-IOS Maybank transaction) 18012017 #24

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#239]
Defect Description : User to reload via FPX, and using IOS mobile. While performing the transaction, 3rd party confirmed as "Successful" transaction, money deducted from user's Maybank account however, the amount does not credited to eWallet account and no message received in user's inbox. 

Issuing bank : Maybank (amount not credited to user's wallet)

Tested with other bank : Successful amount credited via CIMB Bank

Tested for IOS build 14 only. Android no issue.

Refer attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/22054332/01648b36-dd90-11e6-880b-25cfa51b4c82.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054380/40417148-dd90-11e6-88fb-809b28ab3b6a.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054392/509f6a22-dd90-11e6-8eae-df82011429d9.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054396/53fa42fa-dd90-11e6-99c6-bda20a644605.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054397/58334baa-dd90-11e6-951c-62f9ddcda3d3.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054523/f12a68ca-dd90-11e6-93df-d9760b25e712.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054423/7ec8baf2-dd90-11e6-980a-a29d244cf2cc.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054249/90548f86-dd8f-11e6-9667-f1b583af2dac.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22054316/ef5a3ac6-dd8f-11e6-952e-b24ba9a8c667.png)

**Comment by mayyeap** [comment]
Hi Farah, 

Please refer to the email i sent and close the case accordingly. Need bavani to advise.

**Comment by markshermanp** [comment]
Failed transactions will be handled manually e.g. ABL backend generates exception report and Operations team to do reconciliation and to perform refund/reversal when applicable.

email from ipay:
On ipay88 side, our transaction logs show the payment is success and FPX had return response to ipay88 and our BackendURL logs for this transaction also indicate ipay88 had return 3 times to backendurl.

**Comment by markshermanp** [comment]
Closing defect. Reversal/refund to be performed next week
