### ISSUE TITLE
e-Wallet_Mobile App (FPX Reload-iPay88 Email Details) 18012017 #25

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#240]
Defect Description : The "Product Description" fields value displayed wrong. Should not be "Pre-Authorization" as the action performed was "Reload".

Refer attached screenshot.

![image](https://cloud.githubusercontent.com/assets/23113211/22055293/758f5e0a-dd95-11e6-9206-77a65e62b7f3.png)

**Comment by mayyeap** [comment]
Hi Mark, 

Apac venture will make the changes and release the build on monday.

Thanks

**Comment by mayyeap** [comment]
Hi Mark, 

Please test the new build and close the case.

![jofbcggbhbnpblbj](https://cloud.githubusercontent.com/assets/23113169/22201952/de00b556-e1a0-11e6-88fa-d9ee685ebfa9.jpg)

**Comment by farahmohamad** [comment]
![Uploading retest.JPG…]()

**Comment by farahmohamad** [comment]
Hi All,

Retested with Android build 23 and IOS build 18. 
Refer attached screenshot for POT.

Thank you.
![capture](https://cloud.githubusercontent.com/assets/23113211/22236963/c322be2a-e243-11e6-98f7-970422a0e17c.JPG)
