### ISSUE TITLE
e-Wallet_Mobile App (Utilities - Astro Reversal) 20012017 #26

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#241]
Mobile App does not display reversal status for utility payment.

Defect Description : User to perform a "reversal" scenario for utility payment however, mobile application does not indicate the transaction is successful/failed/reverse.

Attached screenshot for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/22144477/d555ec56-df38-11e6-9911-a38abb4ed537.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22144481/d8c40a12-df38-11e6-8516-2199887a1341.png)

**Comment by farahmohamad** [comment]
Hi All,

Tested with build 22 for Android, however the status field is "blank" but at customer service admin portal displayed "reversed" status.

Please refer to screenshot attached for POT.

![image](https://cloud.githubusercontent.com/assets/23113211/22191458/df076638-e165-11e6-9ee6-1a132b370efc.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22191461/e344ce52-e165-11e6-8c2a-ebdcc5a08ab5.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22191466/e8e1624e-e165-11e6-8c9f-178c393b3000.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22191473/ee65feb4-e165-11e6-8b9d-df8e6f72e9f6.png)

**Comment by mayyeap** [comment]
![c74aece5-6278-48c1-8338-0fd988bf0f7b](https://cloud.githubusercontent.com/assets/23113169/22201899/a0b4870e-e1a0-11e6-8ea6-c0351cad4d0d.jpg)

Please test in the latest build and close the case

**Comment by farahmohamad** [comment]
Hi All,

Tested with Android build 23 and IOS build 18.

Retested and passed. 
Therefore, close the defect.

Refer attached screenshot for POT.
![image](https://cloud.githubusercontent.com/assets/23113211/22237131/c5b0fed0-e244-11e6-83cc-e05996999b28.png)
![image](https://cloud.githubusercontent.com/assets/23113211/22237156/e73e9ef4-e244-11e6-8e65-db52766abce8.png)
