### ISSUE TITLE
e-Wallet_Mobile Application (FPX back button not functioning) 23012017 #27

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#242]
Defect Description : When user 3rd party page, example CIMB Bank page, user clicked the back button to return to previous page. However, page displayed error. 

Android no issue as the back button act as "force closed"

![image](https://cloud.githubusercontent.com/assets/23113211/22198741/d6222058-e192-11e6-86ae-df1b024cfa0f.png)

Refer attached screenshot for POT.

**Comment by mayyeap** [comment]
Hi Farah please show bavani the new build and close the case.

**Comment by farahmohamad** [comment]
Retested with build 22 Android and 17 for IOS.

As confirmed with May and Mark,the defect occurs by using the older version of tng app.

Therefore, closed the defect.
