### ISSUE TITLE
e-Wallet_WebAdmin 08112016

### ISSUE THREAD

**Issue by muhdzhrfn** [TNGSB/eWallet#31]
As for today testing, there are 6 defects found in merchant module.

Kindly refer the attached defects document for your perusal.

[Sev_2_08112016.zip](https://github.com/TNGSB/eWallet/files/577780/Sev_2_08112016.zip)

**Comment by JasonABL** [comment]
Changes done as following:
Defect_BackOffice_08112016_#01.xlsx - Merchant name - accept special character.
Defect_BackOffice_08112016_#02.xlsx - Bank A/C - accept alphanumeric
Defect_BackOffice_08112016_#03.xlsx - Company Slogan - accept alphanumeric and space
Defect_BackOffice_08112016_#04.xlsx - Mailing Title - accept alphanumeric and space
Defect_BackOffice_08112016_#05.xlsx - Customer Registration - accept alphanumeric and subtract (-)
Defect_BackOffice_08112016_#06.xlsx - GST Registration No - accept alphanumeric and subtract (-)
