### ISSUE TITLE
eWallet_MobileApp_Bar code & image not refreshing after every 60 seconds # 35

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#35]
The Payment section where the Bar code and image is shown are supposed to refresh after every 60 seconds but even after 5 minutes it still remain the same without being refreshed automatically

**Comment by ArjunLokanath** [comment]
May from ApacVenture advised that the Target Fix Date for this Defect is around mid of November

**Comment by mayyeap** [comment]
fix.  please check latest build

**Comment by ArjunLokanath** [comment]
Retested this issue successfully, Hence closing the defect.. Thanks
