### ISSUE TITLE
eWallet_MobileApp_Unable to Top-up for a valid prepaid number # 40

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#40]
When User tries to top up and recharge for a valid prepaid number (Tunetalk for example) it does not allow to reload and the error message being displayed is: “Please enter a correct phone number”

**Comment by ArjunLokanath** [comment]
May from ApacVenture had advised that the fix for a 11 Digit mobile number recharge should be available in the next build

**Comment by mayyeap** [comment]
11 number fix.please check latest build

**Comment by ArjunLokanath** [comment]
OK Thanks and closing the defect as this was retested successfully

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
