### ISSUE TITLE
eWallet_MobileApp_The QR Code scanner not working for Android phone # 42

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#42]
The QR code scanner does not work for Android phone, Mostly because its in a rectangle shape instead of a square

**Comment by ArjunLokanath** [comment]
As per May - ABL team need to check and advise on this

**Comment by JasonABL** [comment]
Can we have more details of this issue? Kindly attach the email conversations related to this.

**Comment by ArjunLokanath** [comment]
Retested this successfully now hence closing the defect
