### ISSUE TITLE
eWallet_MobileApp_Search button to search for the buddy using the ID on the first page is not working # 43

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#43]
In the RM Transfer module, The first page displayed is the Transfer page with the option to choose the person user wishes to transfer the amount to and this is again repeated on the very next page where the user is again required to enter the name of the buddy and add the same before he can transfer any RM to their accounts making it a redundant process flow

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this defect's Target Fix Date is by mid of November

**Comment by mayyeap** [comment]
fixed, pls test again

**Comment by ArjunLokanath** [comment]
Retested this issue successfully, Hence closing the defect.. Thanks

**Comment by ArjunLokanath** [comment]
Hi May,

Yes the defect has been fixed and retested successfully hence closed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
