### ISSUE TITLE
eWallet_MobileApp_Wrong error message as "Request timed out" being displayed for incorrect Account number and incorrect Transaction Pin # 44

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#44]
Under the Utilities module when the User tries to make a payment on any of the 3 utilities available after the User enters an incorrect Account number and an incorrect Transaction PIN, the system displays the error message as “Request timed out” instead of alerting that the Account number and the Transaction PIN entered by the User is incorrect

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this defect's Target Fix Date is by mid of November

**Comment by mayyeap** [comment]
Please test again

**Comment by ArjunLokanath** [comment]
Hi May,

Just retested this but still fail as message displayed now is "Insufficient
balance" even after entering the incorrect Account number.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by mayyeap** [comment]
can you try at uat?

**Comment by farahmohamad** [comment]
**Hi All,**

Tested with Android, build 38 UAT-Live, and displayed the error message as "invalid PIN"
According to May, IOS will change the wording of error message.

Threrefore, close the defect.

![image](https://cloud.githubusercontent.com/assets/23113211/21168316/06a0f3ea-c1ee-11e6-8843-0697f181553c.png)
