### ISSUE TITLE
eWallet_MobileApp_In the Air Ticket module the flights searched are not retrieving the correct Flight duration details # 45

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#45]
Under the Air Ticket module the flights searched are not retrieving the correct data, For the search made: 
A flight which ideally takes around 4 hours is being shown as 28 hours or a 30 hours flight on the search results

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this defect's Target Fix Date is by mid of November

**Comment by mayyeap** [comment]
UAT is live information, DEV is dummy information. You may download uat build just to check the information.

**Comment by ArjunLokanath** [comment]
Hi May,

The Defect was tested in the Dev environment earlier as advised back then,
Thanks

Hi Bavani,

Please advise if this defect can be closed now or retested in the Live
environment? Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
not required to test
