### ISSUE TITLE
eWallet_MobileApp_In the Air Ticket module the flights searched are not retrieving the correct Pricing details # 46

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#46]
Under the Air Ticket module the flights searched are not retrieving the correct data, For the search made: The pricing should be ideally around RM 400 however the search results is throwing up a very minimal of RM 4.08 or a very high price of RM 1,697.14

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this defect's Target Fix Date is by mid of November

**Comment by mayyeap** [comment]
UAT is live information, DEV is dummy information. You may download uat build just to check the information.

**Comment by ArjunLokanath** [comment]
(Same as the previous email)

Hi May,

The Defect was tested in the Dev environment earlier as advised back then,
Thanks

Hi Bavani,

Please advise if this defect can be closed now or retested in the Live
environment? Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
no need to test as discussed earlier
