### ISSUE TITLE
eWallet_MobileApp_The Android version of the App is not available on Playstore for User to download # 47

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#47]
For a new User who wishes to download the app on Play store from an Android phone, the Touch N Go application is not available on Play store to initiate the download

**Comment by ArjunLokanath** [comment]
APAC venture mentioned that this is part of Beta testing and not available yet

**Comment by ArjunLokanath** [comment]
APAC venture mentioned that this is part of Beta testing and not available yet

**Comment by mayyeap** [comment]
playstore will be ready when it ready to go live (public)

**Comment by ArjunLokanath** [comment]
OK so does that mean that this can be tested in the Live environment?
(Build # 33 for Android or Build # 38 for iOS)

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by mayyeap** [comment]
is only available when the app ready to go live-public. now is still live for tester

**Comment by ArjunLokanath** [comment]
OK noted

Hi Bavani,

Please confirm if we can close these related defects for Android (Play
store) and for iPhone (apple store), Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Kindly advise if we can close this issue now or do we need to keep it open until ready for Public use, Thanks

**Comment by ArjunLokanath** [comment]
Closing this defect as advised by Bavani, Thanks
