### ISSUE TITLE
eWallet_MobileApp_The iOS version of the App is not available on Apple store for User to download # 48

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#48]
For a new User who wishes to download the application on Apple store from an iPad, the Touch N Go application is not available on Apple store to initiate the download

**Comment by ArjunLokanath** [comment]
APAC venture mentioned that this is part of Beta testing and not available yet

**Comment by mayyeap** [comment]
apple store will be ready when it ready to go live (public)

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Kindly advise if we can close this issue now or do we need to keep it open until ready for Public use, Thanks

**Comment by BavaniS** [comment]
Yes close it

**Comment by ArjunLokanath** [comment]
Closing this defect as advised, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
