### ISSUE TITLE
eWallet_MobileApp_When the User enter the incorrect PIN twice after displaying the error message, the system does not display the Login / Registration page # 52

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#52]
As per the alternate flow mentioned under UC 4 in the functional specs, When the User enter the incorrect PIN twice after displaying the error message it is supposed to display the Login / Registration page however it does not take him back to the Login / Registration page

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture there have been changes made to the Functional specs, Bavani to check and confirm if these changes made are fine before this defect can be closed

**Comment by BavaniS** [comment]
user experience exceptional, can skip this.
