### ISSUE TITLE
eWallet_MobileApp_OTP validity is for 3 minutes only however the OTP had not expired even after 5 minutes and the transaction went through when the User tried with the old OTP # 54

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#54]
As per the Table 2 under UC4 it is said that the OTP Pin is valid only for 3 minutes however when the same OTP was used even after 5 minutes, the User was able to proceed completing the registration and no error message was prompted to stop the User from completing the registration process

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this defect is pending investigation from ABL side

**Comment by JasonABL** [comment]
Currently system param configured 30 mins in dev environment.

**Comment by ArjunLokanath** [comment]
Hi Jason,

The test conducted is as per the details mentioned in the Functional Specs,
Hence it will still be considered as a defect if the FS has not been
updated accordingly (30 minutes), Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by JasonABL** [comment]
Hi Arjun,

Understood the document stated default value as 3. But it's dev environment, the value have changed for testing purpose. Have updated back the value to 3. Please try again, thanks.

**Comment by ArjunLokanath** [comment]
I tried to retest this many times but unable to test this accurately even
in the Dev environment because the OTP is being generated only after around
10 minutes time hence the OTP i enter is invalid already,

Objective of the test i exactly after 3 minutes which we are unable to
achieve at the moment.

Dear Bavani,

Please take note as this issue is occurring in the Dev environment as well,
Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Hi Arjun,

If the OTP is expired means the OTP time validation is correct. The delay of receiving OTP is not within our control. May check with Mobility One why this is happening. Thanks.

Regards,

Jason

**Comment by ArjunLokanath** [comment]
Yes I am aware Jason, However the test is not only on the OTP expiry but
also on the time validation meaning I want to check if it consider at 5
minutes or not which was the previous setting, But not able to test this as
I am receiving only around 10 minutes or so, Hope this clarifies.. Thanks

Hi Bavani,

Can please help to check onwards with Mobility One why there is a big delay
in User receiving the OTP's, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Hi Arjun,

Okay, noted. =D

Thanks.

Regards,

Jason

**Comment by markshermanp** [comment]
<Zharfan 2.12.16> Retest OK. Closed.
