### ISSUE TITLE
eWallet_MobileApp_User allowed to register with the first OTP when a second OTP had already been generated and received by the User # 55

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#55]
When a new User is trying to register and after he requested for a new OTP but still able to register using the first OTP (previous one) but system should ideally not allow this and should consider only the second OTP for registering the new User

**Comment by ArjunLokanath** [comment]
May from APAC Venture had mentioned that this needs to be checked by the ABL team

**Comment by JasonABL** [comment]
Hard to determine which is first and second. SMS Gateway may have delayed the sending of OTP. Can show us the OTP(s) you have?

**Comment by ArjunLokanath** [comment]
Hi Jason,

Do not have the screenshots for this issue now, Will retest this and share
the results with you again later.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by raymondabl** [comment]
For your information, we are using time-based OTP, not event-based OTP. So we are unable to trace whether the entered OTP was first request or second request or so forth.

**Comment by BavaniS** [comment]
otp need to be 3 minute because 1 minute is too short and most users having issue now receiving otp

from abl side remains
apac to make the changes on otp time out counter from 60 second to 3 minute

**Comment by ArjunLokanath** [comment]
Understand Raymond, however since we are using time-based OTP - Should the
system consider the OTP generated at an earlier time as the first OTP and
so forth based on the time at which each of these OTP's were generated?
Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by mayyeap** [comment]
![b54057c7-a779-4b44-92af-7cf9f0e963c8](https://cloud.githubusercontent.com/assets/23113169/20453586/2d76d8a0-ae65-11e6-817a-891030b1f074.jpg)

**Comment by mayyeap** [comment]
Please test next build on wednesday

**Comment by ArjunLokanath** [comment]
Ok will get my team to retest this next wednesday, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
<Zharfan 2.12.16> Retest OK. Closed.
