### ISSUE TITLE
eWallet_MobileApp_The User Account is not being locked out even after 3 failed attempts to login # 56

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#56]
The second Business Rule stated under UC5 states that the User Account would be locked out after 3 failed attempts to login, however even after 5 failed attempts the User is still allowed to login after entering the correct password

**Comment by ArjunLokanath** [comment]
May from APAC Venture had mentioned that this needs to be checked by the ABL team

**Comment by JasonABL** [comment]
Currently system parameter is set to 5 times. Can try if failed to login for 5 times?

**Comment by ArjunLokanath** [comment]
Hi Jason,

The test conducted is as per the details mentioned in the Functional Specs,
Hence it will still be considered as a defect if the FS has not been
updated accordingly (5 times), Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by raymondabl** [comment]
This is indeed a problem with the backend. Will update again once mitigate the problem.

**Comment by BavaniS** [comment]
abl changed parameter from 5 to 3. 

abl to return proper response code to apac.

apac to alert user by giving pop up (similar like pin)

**Comment by ArjunLokanath** [comment]
Thanks Raymond and any update on this fix? Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by JasonABL** [comment]
Hi,

Bug have fixed, please retry for testing.

Regards,
Jason

**Comment by ArjunLokanath** [comment]
Hi Jason,

Just tested on the Android version now and after 3 incorrect passwords the
error message: "Invalid Customer" is being displayed however the
expectation is that the User knows he/ she is being locked out due to 3
consecutive invalid attempts and User have to call the Customer service to
unblock so kindly help to correct this, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Adding on, It was also noted that the User Account was locked out after 3
times on iOS whereas it locked out after 6 times on Android version.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Hi Arjun,

I’m not sure why this happening, API are standards. It’s not possible having different counts of failed attempts for IOS and Android.

Please check with Apac.

Regards,

Jason

**Comment by ArjunLokanath** [comment]
Hi May,

Please advise on the below issue that has not been resolved fully, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
<Farah 7.12.16> retest at Live, still not OK. Defect reopened

**Comment by markshermanp** [comment]
@JasonABL as discussed pls relook into the issue; still happening at Dev

**Comment by JasonABL** [comment]
fixed, kindly retry.

**Comment by markshermanp** [comment]
retested OK, closing defect
