### ISSUE TITLE
eWallet_MobileApp_The First User (Original User) gets logged out from the application when another User successfully logs in from another device # 57

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#57]
When the User has already logged in from a device and attempts to login from another device then the user who is attempting to login from another device must be stopped with an error message and not the User who had already logged in originally

**Comment by ArjunLokanath** [comment]
Bavani to help provide direction as per the correct logic for this

**Comment by BavaniS** [comment]
latest login should override the previous login

let me know if any issue otherwise close this

**Comment by ArjunLokanath** [comment]
Closing this defect as confirmed by Bavani that the latest login should override the previous login
