### ISSUE TITLE
eWallet_MobileApp_The Copy Icon to enable the User to copy an existing merchant profile details to help create a new profile is missing # 59

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#61]
As per the Functional Specs – 3.5.2.2.5, there should have a Copy icon in the Merchant Listing page so that the User can copy the Merchant profile to a new profile however this icon itself is missing

**Comment by JasonABL** [comment]
Have updated the spec as the function removed.

**Comment by ArjunLokanath** [comment]
Noted Jason, Kindly let us know which version of the FS to refer for this
update.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by raymondabl** [comment]
We have shared latest spec with TNG
1. e-wallet_functional_specsv3.2.6.docx
2. e-wallet_functional_specs-financials_ops_tngv3.3.5.docx

Please request from Bavani.

**Comment by BavaniS** [comment]
doc shared, arjun to verify and close.

**Comment by ArjunLokanath** [comment]
Updated Doc shared by ABL, Hence closing this defect as the FS has been
updated

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
