### ISSUE TITLE
eWallet_MobileApp_The Overall Touch sensitivity on the application needs to be greatly improved # 62

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#66]
The Application’s overall touch sensitivity needs to be improved and especially at the “History” tab on the Home screen

**Comment by mayyeap** [comment]
Already informed developer but is not under our control for the sensivity. It depend on devices

**Comment by BavaniS** [comment]
apac claims sensitivity increased to the max already

**Comment by ArjunLokanath** [comment]
As per Bavani's comment, This defect has been closed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
