### ISSUE TITLE
eWallet_MobileApp_The Terms and Conditions mentioned on the T & C page is incomplete # 63

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#67]
The Terms and Conditions page does not have the full list of terms and conditions, it ends abruptly with the word “Or”

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture team the Terms and Conditions were updated as per the info provided by TnG until date, For further updates the same is required to be provided by TnG, Bavani to help provide direction on this.

**Comment by mayyeap** [comment]
final TNC will be completed in the next build

**Comment by ArjunLokanath** [comment]
Reopening this defect as this needs to be retested in the next build before closure

**Comment by BavaniS** [comment]
any defect you need to retest assign to yourself

**Comment by ArjunLokanath** [comment]
Hi Bavani,

Noted on the other FAQ defects and agree that we will keep only this defect
as Once case for all FAQ related issues, Thanks and will retest this once
fixed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by markshermanp** [comment]
retested at Live, working OK. Defect closed.
