### ISSUE TITLE
eWallet_MobileApp_The Third FAQ section is incomplete # 66

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#70]
The FAQ section’s third FAQ “3. How to reload the wallet” does not have any sensible information upon clicking the question for the FAQ answer

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture team the FAQ sections were updated as per the info provided by TnG until date, For further updates the same is required to be provided by TnG, Hence Bavani to help provide direction on this.

**Comment by mayyeap** [comment]
latest faq will be reflected in next build

**Comment by ArjunLokanath** [comment]
Reopening this defect as this needs to be retested in the next build before closure

**Comment by markshermanp** [comment]
The defect has been fixed and retested successfully hence closed
