### ISSUE TITLE
eWallet_MobileApp_The Fourth FAQ section is incomplete # 67

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#71]
The FAQ section’s fourth FAQ “4. How to redeem voucher” does not have any sensible information upon clicking the question for the FAQ answer

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture team the FAQ sections were updated as per the info provided by TnG until date, For further updates the same is required to be provided by TnG, Hence Bavani to help provide direction on this.

**Comment by mayyeap** [comment]
latest faq will be reflected in next build

**Comment by ArjunLokanath** [comment]
Reopening this defect as this needs to be retested in the next build before closure

**Comment by BavaniS** [comment]
duplicate #70 . just keep once case opened
