### ISSUE TITLE
eWallet_MobileApp_The Login ID used to register should be identical to the User's name # 69

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#73]
As per the Functional Specs – Section: UC3, The User should register with a name that should be identical with the ID however there is no validation to check this, for example: Name entered is ‘Arjun’ and the Login ID entered is ‘Tester’ but the User is still able to proceed completing the registration

**Comment by ArjunLokanath** [comment]
<May> It is because, different user might have the same name, but login ID for each individual is unique. We only do validation check on user IC, that why is not applicable.
<Arjun> OK, So are we amending the FS section? – UC3 so that the name validation is removed and replace with only IC validation?

**Comment by BavaniS** [comment]
no kyc. no control on user's choice
