### ISSUE TITLE
eWallet_MobileApp_The User is allowed to register with a name that is greater than 65 characters in length # 70

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#74]
As per the Functional Specs – Section: UC3, The User should register with a name that should be maximum of 65 characters however there is no validation to check this, for example: When User enter a name, which is of 78 characters in length the User is still able to proceed completing the registration

**Comment by ArjunLokanath** [comment]
May from APAC Venture has agreed to fix this by limiting the length to 65 characters, Awaiting the fix to be done so that the same can be retested

**Comment by mayyeap** [comment]
length already fix in tested build, please check

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
