### ISSUE TITLE
eWallet_MobileApp_The User is being allowed to register with a name of only One character in length # 71

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#75]
The User should register with a name that should be minimum of 2 characters and lesser than that is not allowed however there is no validation to check this, for example: Name entered is ‘A’ but the User is still able to proceed completing the registration

**Comment by ArjunLokanath** [comment]
This was not mentioned originally as a Requirement and hence not built, Bavani to help provide direction on this issue now

**Comment by BavaniS** [comment]
user's choice, we do not control if user does not follow name as per ic
