### ISSUE TITLE
eWallet_MobileApp_Inbox details displayed for a Reload transaction done is very brief # 74

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#78]
When there is a reload that is done the details displayed in the inbox is very brief as “eWallet reloaded” without Date or time so that User need not have to open the message to see all details

**Comment by ArjunLokanath** [comment]
Bavani to provide direction on this defect and this issue was identified by her, As per APAC (May) - Due to Space limitation this will be in UI change in future when TnG revised the existing UI. Currently will remain the same. Transaction notification might be removed from inbox as per the CEO's comments

**Comment by BavaniS** [comment]
to be managed by ui/ux change
