### ISSUE TITLE
eWallet_MobileApp_More detailed and User friendly SMS message to be sent to the User when the User forgets the Login ID and requests for the same to be sent by SMS # 75

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#79]
As per UC6 when User forgets the Login ID and requests for the same by entering the ID number and also selecting the ID type a SMS is sent to the Customer with the Login ID mentioned therein however the SMS sent says “Login IDs” when there is only a single Login ID mentioned and also the message can be more user friendly, For example: “Your eWallet Login ID is: XXXXX”

**Comment by ArjunLokanath** [comment]
May from APAC Venture had mentioned that this needs to be checked by the ABL team

**Comment by JasonABL** [comment]
This is only cosmetic change, need Bavani to agree and not priority for now.

**Comment by BavaniS** [comment]
TNG to tell abl what is the sms content

**Comment by ArjunLokanath** [comment]
Noted Jason

Hi Bavani,

This was raised by the FUT user so can you please advise if we can close
this issue or defer it to a later time in the future? Thankss

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
check with me next week

**Comment by farahmohamad** [comment]
![image](https://cloud.githubusercontent.com/assets/23113211/20917651/ae94b914-bbcd-11e6-879f-a1140361dd04.png)

Tested today 6/12/2016 in build 38 live environment. 
Close this defect
