### ISSUE TITLE
eWallet_MobileApp_Full name is being concatenated wherein the First name & Last name of the User is being displayed as a single name after the User completes registration # 76

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#80]
At the time of registration when the Customer enters a Full name with a space between the first name and the last name however post registration the Space provided at the time of registration is not captured and the two words are displayed as a single name

**Comment by mayyeap** [comment]
fix, will be in next build

**Comment by BavaniS** [comment]
check after 18 nov

**Comment by farahmohamad** [comment]
Tested with both environment Live (Android 38) and for development environment (IOS 48)

Close this defect.

![image](https://cloud.githubusercontent.com/assets/23113211/20917852/d6f9a058-bbce-11e6-93cc-3ac1c7c3abd3.png)
![image](https://cloud.githubusercontent.com/assets/23113211/20917860/e05a6fa6-bbce-11e6-93ca-eb5cb5f26767.png)
![image](https://cloud.githubusercontent.com/assets/23113211/20917866/e88d42f2-bbce-11e6-988c-b5a808a06000.png)
![image](https://cloud.githubusercontent.com/assets/23113211/20917869/f1c83ed0-bbce-11e6-950f-ebd8978f5d48.png)
