### ISSUE TITLE
eWallet_MobileApp_On the Registration Page the 'Password' and the 'Confirm Password' fields are not aligned # 77

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#81]
After clicking the Register button on the starting page once the Mobile app has been downloaded, At the Register page the 'Confirm Password' is not aligned to the 'Password' text field

**Comment by ArjunLokanath** [comment]
As per May from APAC venture this defect has been included as part of their Bug list

**Comment by mayyeap** [comment]
cosmetic, will ask bavani whether this need to change

**Comment by BavaniS** [comment]
covered as part of ui/ux change
