### ISSUE TITLE
eWallet_MobileApp_Message displayed when User clicks on the 'My Rewards' tab to be corrected # 78

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#82]
After clicking the ‘MyRewards’ tab which takes user to the coming soon page wherein the first line can be changed to “We are coming soon…” instead of “We are soon coming…”

**Comment by ArjunLokanath** [comment]
As per May from APAC venture the Loyalty section will only be ready by 14 November

**Comment by mayyeap** [comment]
This to be delay to 18 nov

**Comment by BavaniS** [comment]
NA until loyalty kicks in

**Comment by ArjunLokanath** [comment]
Reopening this defect as this needs to be retested in the next build before closure

**Comment by ArjunLokanath** [comment]
Still waiting for the Loyalty build to come in.

**Comment by BavaniS** [comment]
This not an issue, close it.

**Comment by ArjunLokanath** [comment]
Closing this defect as advised, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
