### ISSUE TITLE
eWallet_MobileApp_ The Start Date and End Date in the History tab after selection should be in the DD/MM/YYYY format # 79

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#83]
Under the History Tab - The Start Date and End Date after selection should be reflected in the universally followed DD/MM/YYYY format and not in the YYYY/MM/DD format

**Comment by ArjunLokanath** [comment]
As per May from APAC venture has included this defect as part of their Bug list

**Comment by mayyeap** [comment]
Bavani to make decision on the changes

**Comment by BavaniS** [comment]
part of ui/ux change
