### ISSUE TITLE
eWallet_MobileApp_The First FAQ section has not been correctly spelt and punctuated # 80

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#84]
The FAQ section’s first FAQ “1. What’s Touch ’n Go Wallet” is not correctly spelt and punctuated

**Comment by ArjunLokanath** [comment]
Bavani to help provide the info to APAC Venture so that the FAQ sections can be correctly updated

**Comment by mayyeap** [comment]
Will be updated in next build

**Comment by BavaniS** [comment]
FAQ taken care of separately

**Comment by ArjunLokanath** [comment]
Reopening this defect as this needs to be retested in the next build before closure

**Comment by markshermanp** [comment]
retest at Live is OK. closing this defect
