### ISSUE TITLE
eWallet_MobileApp_Wrong error message displayed to the User when the User keys in a special character in the Password during the Registration stage # 81

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#85]
On the Register page when the User keys in a special character in the Password field then User is not allowed to proceed with the registration as special characters are not allowed however the error message displayed states “Password must be 8-15 alphanumeric characters, at least one upper case”

**Comment by ArjunLokanath** [comment]
APAC venture is working on this and have confirmed to change the error message

**Comment by mayyeap** [comment]
fara already raise this before. Please check with her

**Comment by BavaniS** [comment]
check in live env and close

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed
