### ISSUE TITLE
eWallet_MobileApp_Wrong error message displayed to the User when the User keys in more than 20 characters in the ID Number field # 82

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#86]
When the User keys in more than 20 characters in the ID Number field at the Registration page then the system displays the error message: “System_Error” instead of stating that the ID number is more than 20 characters in length

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture a fix would be made to limit to 20 characters, Expected to come in the next build

**Comment by mayyeap** [comment]
fara already raise this before. Please check with her

**Comment by ArjunLokanath** [comment]
This was raised originally as part of the Word document related defects on
the previous build,

The defect raised by Farah is a reopened defect on Build # 31, Will retest
now and close if working fine, Hope this clarifies.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed
