### ISSUE TITLE
eWallet_MobileApp_Wrong error message displayed to the User when the User keys in special character in the ID number field during the Registration stage # 83

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#87]
When the User keys in special character in the 'ID Number' field at the Registration page then the system displays the error message: “System_Error” instead of stating that special characters are not allowed in the 'ID Number' field

**Comment by ArjunLokanath** [comment]
APAC venture is working on this and have confirmed to change the error message

**Comment by mayyeap** [comment]
fara already raise this before. Please check with her

**Comment by ArjunLokanath** [comment]
Retested this Defect and it is allowing even a single character as a
Special character ($ - Dollar symbol) hence reopening this defect as the
retest has failed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by JasonABL** [comment]
our system has the backend validation checking on the loginId. Frontend should also do this validation and not allow customer to register.

**Comment by ArjunLokanath** [comment]
Hi May, Please see the message from Jason above and kindly look into this defect please, Thanks

**Comment by mayyeap** [comment]
Bavani, 
Please advise is other ID, police or amy got special character?

Thanks

**Comment by BavaniS** [comment]
may - all alphanumeric only, same as IC. this as captured in your ppt just now.

arjun - retest after new build.

**Comment by ArjunLokanath** [comment]
Noted Bavani, Thanks

Hi Farah,

Please help to retest this on my behalf once the new build is released on
Monday, Thanks



Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by farahmohamad** [comment]
Closed by bavani previously.

**Comment by farahmohamad** [comment]
Retested with live environment and system displayed invalid ID No. 

Therefore, closed.
