### ISSUE TITLE
eWallet_MobileApp_Improvement required on the error message displayed to the User for entering an existing Login ID at the Registration stage # 84

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#88]
When a new User is trying to register, but enters an existing Login ID then the User is stopped from registration with the error message displayed as: “LOGIN_ID_ALREADY_EXISTS” however this format can be improved with a friendly error message displayed in normal text without any underscore and all Capital letters, for example: “Login ID already exists, please enter another Login ID”

**Comment by ArjunLokanath** [comment]
As per APAC Venture - Still finding solution to fix the error messages. Hopefully will be done by mid november

**Comment by BavaniS** [comment]
covered as part of error mapping
