### ISSUE TITLE
eWallet_MobileApp_No indication or message after the User clicks "Allow notifications" # Live_001

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#89]
After click allow notifications, the screen remains static, no messages or indication on what to do, until I swipe right and see "Let's go" button on next page

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by ArjunLokanath** [comment]
Updated the Defect number accordingly as this was raised in the Live environment

**Comment by mayyeap** [comment]
There is 2 button at the bottom show as indication there is next page, something like air asia website.

**Comment by mayyeap** [comment]
![872ab84c-e471-45a5-8ded-dcc9e2b41b51](https://cloud.githubusercontent.com/assets/23113169/20348739/06ab68e6-ac42-11e6-94b7-f85d5f105911.jpg)

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
