### ISSUE TITLE
eWallet_MobileApp_On the Registration page, the Name field was not appearing during the registration process # Live_002

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#90]
For Registration, I cannot see the field to click. I tried clicking the Name*, nothing happened, then click to the right of the Name*, then only the Cursor & Keyboard appears.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
can u check again?

**Comment by mayyeap** [comment]
Bavani please advise.

**Comment by ArjunLokanath** [comment]
The defect has been fixed and retested successfully hence closed

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
