### ISSUE TITLE
eWallet_MobileApp_For a masked field the User cannot edit the field such as to change the first character or the last character as it clears all the text in the field # Live_003

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#91]
For a masked field,  we cannot edit the field such as to change the first character, or even the last character. The moment we type something or back keyboard, it will clear the entire field. Shouldn't the field behaves like a normal field (non-masked) when editing?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
depend on phone, Ios will clear the whole field, android will delete the selected

**Comment by mayyeap** [comment]
Bavani, please advise

**Comment by ArjunLokanath** [comment]
Hi May,

So is this a phone constraint?

Or the code written differently for each of these variants? Please confirm,
Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
coders programming knowledge limitation, arjun close the defect.

may - update this in the ppt, in future once ui ux change this should be taken care of.

**Comment by mayyeap** [comment]
done please close

**Comment by mayyeap** [comment]
Hi Bavani and Arjun, 
I just check with my developer on this, this issue cause by system contraint.
IO original system, encrypted words will be deleted onece, eg password but plan text can be deleted one by one eg. login ID, phone nymber and etc. Please test again as this is not something that my developer can control.
Thanks

**Comment by ArjunLokanath** [comment]
OK noted with Thanks May

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by ArjunLokanath** [comment]
Noted Bavani, Closing this defect now.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
