### ISSUE TITLE
eWallet_MobileApp_The FPX Reload Page is very slow and hanging and showing a blank screen to the User # Live_004

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#92]
FPX Reload Page is slow & showing blank. Users don’t realize whether it is loading or hang or nothing is really happening, as the loading indicator on top of the page is too thin to notice.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
please ask Bavani to talk to Ipay88

**Comment by ArjunLokanath** [comment]
Hi Bavani,

This defect was identified by the FUT user, Kindly help to provide
direction on this issue.. Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
check after 25 nov
