### ISSUE TITLE
eWallet_MobileApp_FPX screen not re-positioned to the last click # Live_006

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#94]
When click the change tag, screen goes back to top, need to scroll back down and right to enter the tag number. After key-in Tag, goes back to top left. Can't the FPX screen be repositioned to last click?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
please check with ipay or check uat

**Comment by ArjunLokanath** [comment]
Hi Bavani,

We do not have a contact at iPay, Can you please help to liaise with them..
Thanks a lot

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870

**Comment by BavaniS** [comment]
already inform ipay, check after 25 nov.

**Comment by ArjunLokanath** [comment]
Noted Bavani, Will retest this after 25 Nov.
Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
