### ISSUE TITLE
eWallet_MobileApp_Wrong error message displayed when the User tries to cancel a FPX transaction # Live_007

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#95]
After selecting Deno, then Proceed button then user wanted to cancel the transaction, so the user click the <Back button, the following error displayed "FPX Error, We are currently experiencing technical glitch. Please try again later. ….. ". 

Everytime we do this, we will get an email notification from FPX, with Debit Status "1 F (Failed due to  BUYER CHOOSE CANCEL AT ACCOUNT SELECTION PAGE)". 
Is this how it should behave?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
please check with ipay88

**Comment by BavaniS** [comment]
send me screenshot or detailed email to take it with ipay

**Comment by ArjunLokanath** [comment]
Hi Bavani,

This was identified by the FUT user and I am not able to replicate this
test because I dont have an iPhone with me now and this was encountered by
the User while testing using the iOS, Thanks

Best Regards,
Arjun Lokanath
Test Manager, AppSync
Malaysia HP: 01135443870
