### ISSUE TITLE
eWallet_MobileApp_User cannot go back to main app when clicking Back button and need to click the Close button instead # Live_008

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#96]
User cannot go back to main app when clicking <Back button and need to click the Close button instead. 
The <Back button and Close too close to each other. 
What is the difference between the 2 buttons here? 
When do we use Back and when do we use Close?

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
Back is go back the previous page, close is close the function .

**Comment by muhdzhrfn** [comment]
<Mark 01.12.2016> Not an issue,closing the defect.
