### ISSUE TITLE
eWallet_MobileApp_App becomes non-responsive and hangs, User had to close the app and reopen again in order to proceed # Live_009

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#97]
App becomes non-responsive on Friday, 4 Nov, at 5:47pm. Need to press Iphone Home button (minimize) and reopen, then only it moves to next page, but when click again, nothing happens (like it is hang). 
When Close the app, reopen then only it becomes responsive. Unable to simulate this again. 
Elaine witnessed this on my phone.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 04 in the Live environment

**Comment by mayyeap** [comment]
we are not sure the error as we not facing this, can u check again?

**Comment by muhdzhrfn** [comment]
<Mark 01.12.2016> Closing this as not related to functional. Will have this brought up during performance testing if problem persists.
