### ISSUE TITLE
eWallet_MobileApp_Camera not functioning until the User goes to settings and turns on the camera in the iPhone settings # Live_011

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#99]
Camera function not working when updating profile. It shows Black Screen. When I go to Iphone Settings for the App, it shows that the Camera is turned Off. Is this Off by default? Does the app need to prompt user to enable it if it is off? Otherwise, user does not know, and will report the camera is not functioning.

**Comment by ArjunLokanath** [comment]
This issue was identified by the FUT User - Zaly on Nov 07 in the Live environment

**Comment by mayyeap** [comment]
we already default the camera to be on, can u check with other iphone?
